### ISSUE TITLE
recent update has broken use with MongoDB

### ISSUE THREAD

**Issue by vesper8** [GeneaLabs/laravel-model-caching#105]
Unfortunately I don't know exactly what caused it yet and I don't have time to dig in right now. I've had to disable the use of this on my sole MongoDB model for the time being.

What I do know is that it was working before and just now I ran composer update which upgraded this package
```
(0.2.47 => 0.2.52)
```

And now all of a sudden it looks like whenever I make updates/saves to my mongodb model, it doesn't flush/update the cache

Or perhaps more specifically.. I use HybridRelations between my Mysql and MongoDB models

So that my $user is a normal eloquent mysql model and my $profile is a mongo model, but there's a hybrid relation between them. So when I do things like $user->profile->someValue = "newValue"

It doesn't seem to persist the change to the cache (or doesn't cause the cache to be updated)

I'll have to do more testing to try and narrow what happened and what may have caused it to break.. but perhaps you have an idea what might have caused it by looking at the upgraded version numbers above?

It would be super swell if you took the time to get https://github.com/jenssegers/laravel-mongodb working on your machine so you could officially support it :)

**Comment by mikebronner** [comment]
@vesper8 Thanks for reporting this. Unfortunately I don't have an actual use-case or implementation for it, which makes implementing and maintaining it hard. I would love to accept a PR that sets up tests for this, so it is simply part of the testing process.

**Comment by vesper8** [comment]
Ok.. I understand.. I'm not sure how those tests would work.. meaning.. they would only run if they can somehow detect that they are being run from a machine that does have MongoDB set up?

Anyway I will close this for now but will reopen it once I can add more diagnostics and once I have a small reproducible sample which should be shortly

**Comment by mikebronner** [comment]
Thanks @vesper8, I appreciate you digging into the Mongo aspect!

The tests would always test for MongoDB compatibility, there would be no auto-detection process, to make sure the functionality works with mongo as well as RDBMS'.
