### ISSUE TITLE
delete cached data after insert

### ISSUE THREAD

**Issue by jihadismail8** [GeneaLabs/laravel-model-caching#108]
hi , i know there is a method to disable cache  on query , and thats for get requests , i think it would be good to have a method  to remove or delete cached data for a spacific model after an insert , so that the next get request will be a fresh  data from the database . i think this approch is better , because  in our code  we always have  more get requests then inseret or update ones . so instead of coding the disable cache method on each get query  , we can simply code the delete cached  on each insert or update query  ( which are fewer then the get ones ) to get the fresh data , 
thanks :)

**Comment by rssawhney** [comment]
@jihadismail8 it is already handled by the package for inserts and updates
https://github.com/GeneaLabs/laravel-model-caching#features

**Comment by jihadismail8** [comment]
can not find it , could you please write here in summery how is it done  please ?

**Comment by rssawhney** [comment]
@jihadismail8 it is automatically handled by package using laravel's model observers and model events

**Comment by jihadismail8** [comment]
so i have a question , if i have a table with list of cars owned by someone , and on that model i use  cachable trait ,  now if i  insert a new car into the table , and then i try to get and list those cars  it would be completely updated ?

**Comment by rssawhney** [comment]
yup

**Comment by mikebronner** [comment]
Thank you @rssawhney for explaining everything! @jihadismail8 he is right, the main purpose of this package is to automate the caching process. You should only use `->disableCache()` in very few circumstances. :) I'll close this issue. Please don't hesitate to open a new issue, should you run into any problems. :)
