### ISSUE TITLE
Not adding conditionals inside nested model relations

### ISSUE THREAD

**Issue by Tachii** [GeneaLabs/laravel-model-caching#109]
# Issue
Hello,
I have a query :

```
ProductType::where('id', $typeId)->with([
    'relation.subRelation.subSubRelation' => function ($query) {
        dd('test');
        $query->where('product_id', 10);
    }])->first()->toArray();

```
All of the models inside this query use Cachable trait.  But it doesn't enter inside callback. After code execution php doesn't die and doesn't dump 'test'. If I remove catchable trait from all models, it starts working as expected, and just pulls every record for subSubRelation of my query, without using $query->where()

## Environment
Laravel Version: *5.6.15*
Laravel Model Caching Package Version: *0.2.52*
PHP Version: *7.2.1*

**Comment by mikebronner** [comment]
Thanks for reporting this! It will probably take me a few days to get back to you, but wanted to let you know that its on my radar. :)

**Comment by Tachii** [comment]
Just a note, If I add `->disableCache()` it starts working as well.

**Comment by mikebronner** [comment]
@Tachii I was not able to reproduce the issue. Could you test again with the latest version? In my tests it does enter the closure and does trigger the `dd()`:

```php
        $author = (new Author)
            ->where("id", 1)
            ->with([
                'books' => function ($query) {
                    $query->where("id", "<", 100);
                    dd($query);
                }
            ])
            ->first();
```

**Comment by Tachii** [comment]
@mikebronner you relation 'book' is single level, you'll a relation that has another relation in it. Also I'm initializing it with static call. My example still not working:

```
$productType = Type::find($typeId);
$productType = $productType->with([
    'attributeSet.attributes.values' => function ($query) {
        dd('test');
        $query->where('product_id', optional(\request()->product)->id);
        $query->where('webshop_id', \request()->webshop ?? Product::getDefaultWebshopId());
    }])->first()->toArray();
```

**Comment by mikebronner** [comment]
Thanks for the additional explanation. I'll add some tests for that and report back this weekend. Thanks!

**Comment by mikebronner** [comment]
I created another test specific for multiple levels of relationships, but still am not able to reproduce the problem. Please provide a complete stacktrace to troubleshoot this some more. You problem is likely elsewhere in your code. My guess is that your related models might not be cachable.

**Comment by JamesPJ** [comment]
This issue is haunting me in `0.6.0` version as well. We get the cached values even though the query within the relation is changed. 

For example: 

```
    $author = (new Author)
            ->where("id", 1)
            ->with([
                'books.publisher' => function ($query) {
                    $query->where("id", "<", 100);
                }
            ])
            ->first();
```

and now change to 

```
$author = (new Author)
            ->where("id", 1)
            ->with([
                'books.publisher' => function ($query) {
                    $query->where("id", "<", 50);
                }
            ])
            ->first();
```

this will return the previously cached values.
