### ISSUE TITLE
Dynamic setting of cache-prefix causes segfault 11

### ISSUE THREAD

**Issue by madsem** [GeneaLabs/laravel-model-caching#112]
# Issue
I'm developing a multi-tenant, multi-domain app and trying to set the cache-prefix dynamically (based on domain name) in the BaseModel.

When I try to resolve the Domain model from the Servicecontainer the server crashes, artisan commands don't work anymore and return a segfault error signal 11.

## Environment
Laravel Version: v5.6.16
Laravel Model Caching Package Version: 0.2.52
PHP Version: 7.2.4-1
Homestead Version: /
Operating System & Version: Ubuntu 16.04.1

## Stack Trace
no stack trace, causes segfault with signal 11. And NGINX returns server error.

Just using a string as cache prefix works, but as soon as I uncomment the below code everything goes to hell :)
```php
use Illuminate\Database\Eloquent\Model;

use GeneaLabs\LaravelModelCaching\Traits\Cachable;

abstract class BaseModel extends Model
{
    use Cachable;

    /**
     * The domain IoC instance
     * @var $domain
     */
    protected $domain;

    public function __construct($attributes = [])
    {
        //$this->domain = resolve(Domain::class);
        //config(['laravel-model-caching.cache-prefix' => $this->domain->hostname]);

        parent::__construct($attributes);
    }
}
```

Example of an artisan command and result:
```shell
(master *+) landingpages.vm $ php artisan cache:clear
Segmentation fault: 11
```

**Comment by mikebronner** [comment]
Thanks for reporting this!

**Comment by madsem** [comment]
PS: nginx version: nginx/1.13.12

**Comment by mikebronner** [comment]
@madsem What is the output when you do this: 

```php
dd($this->domain->hostname);
```

**Comment by mikebronner** [comment]
@madsem I'll close this for now, please re-open if the problem persists. I haven't been able to reproduce the problem.
