### ISSUE TITLE
[Feature Request] Clear cache of a single model instance

### ISSUE THREAD

**Issue by d3radicated** [GeneaLabs/laravel-model-caching#115]
Right now, it clears all of the model's cache when `flushCache` is called. Suggestion is to allow cache clearing for a single model instance or a collection of models (e.g. clear the cache of models by query).

**Comment by mikebronner** [comment]
Hi @d3radicated , unfortunately there is no way to remove a single model instance from cache due to the way the cache is built. Or are are asking to flush the cache pertaining to a give model class?

Can you explain why you want to use this, so I can better understand your requirements?

Thanks!

**Comment by d3radicated** [comment]
Oh, i see. I haven't been able to dabble with how the cache is built.

I just noticed that when a cached model's relation is updated, the cached model is not updated.

**Comment by mikebronner** [comment]
Ah, that sounds like a bug. Could you provide some code to replicate the issue? Thanks!

**Comment by d3radicated** [comment]
Don't know how to provide it but the gist of it is like this:

A blog (cached) belongs to one author (not cached). Whenever I query for a list of blogs with authors, the collection is cached along with the relation (right?). Now, when I update the author (e.g. disabled the author's account) and run the same query again, the author relation is not updated.

**Comment by mikebronner** [comment]
I would need example eloquent queries, so that I can recreate them in a test. Often times the issue lies in how the queries are built, and not necessarily with the package. Providing concrete examples will help me test and eliminate any misunderstanding. :)

**Comment by d3radicated** [comment]
Sorry for the late reply. I haven't checked back if the issue still exists since we just clear the blog cache when an author is updated. I'll get back to you when we do some code clean-up. Thanks. :)
