### ISSUE TITLE
NotInSub not handled in where

### ISSUE THREAD

**Issue by G89Angel** [GeneaLabs/laravel-model-caching#116]
# Issue
I reached getTypeClause with a $where["type"] === 'NotInSub' which doesn't have an operator. That case is not handled in code.

## Environment
Laravel Version: *5.6.16*
Laravel Model Caching Package Version: *0.2.52*
PHP Version: *7.1.2*
Homestead Version: *7.3..0*

## Stack Trace
```
8
"Undefined index: operator"
"____/src/CacheKey.php"
101
array:1 [▼
  "where" => array:4 [▼
    "type" => "NotInSub"
    "column" => "tax_type_translations.tax_type_id"
    "query" => Builder {#5362}
    "boolean" => "and"
  ]
]
```

**Comment by mikebronner** [comment]
Thanks for reporting this, can you provide an example eloquent query I can use for testing? Thanks!

**Comment by G89Angel** [comment]
This is the resulting SQL:
```select `tax_types`.`id`, `tax_type_translations`.`name` from `tax_types` left join `tax_type_translations` on `tax_type_translations`.`tax_type_id` = `tax_types`.`id` where (`tax_type_translations`.`locale` = ? or (`tax_type_translations`.`locale` = ? and `tax_type_translations`.`tax_type_id` not in (select `tax_type_translations`.`tax_type_id` from `tax_type_translations` where `tax_type_translations`.`locale` = ?)))```

Hard to get it, as it's being generated by LaravelTranslatable: 
https://github.com/dimsav/laravel-translatable

I'm not sure but maybe any kind of eloquent query resulting in a "not in (subselect)" might trigger the problem.

**Comment by G89Angel** [comment]
I'm not sure about how can I get it, since it's being generated by a vendor component.

Basically I do my query like this:
```TaxTypes::withTranslation()->get();```

What happens there is harder for me to tell, this is the scope:
```/**
     * This scope eager loads the translations for the default and the fallback locale only.
     * We can use this as a shortcut to improve performance in our application.
     *
     * @param Builder $query
     */
    public function scopeWithTranslation(Builder $query)
    {
        $query->with([
            'translations' => function (Relation $query) {
                if ($this->useFallback()) {
                    $locale = $this->locale();
                    $countryFallbackLocale = $this->getFallbackLocale($locale); // e.g. de-DE => de
                    $locales = array_unique([$locale, $countryFallbackLocale, $this->getFallbackLocale()]);

                    return $query->whereIn($this->getTranslationsTable().'.'.$this->getLocaleKey(), $locales);
                }

                return $query->where($this->getTranslationsTable().'.'.$this->getLocaleKey(), $this->locale());
            },
        ]);
    }```

**Comment by G89Angel** [comment]
After a review I think this might be launched because of the locale fallback:
https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php#L549

It looks more like the troublemaker

**Comment by mikebronner** [comment]
Unfortunately I'm unable to troubleshoot 3rd-party packages. Could you post a public test repo with the plugin that recreates the problem? That way I could download and run the repo and see what's going on.

**Comment by mikebronner** [comment]
@G89Angel I'll close this for now, but please re-open if you still have this issue.

**Comment by DmitrySkibitsky** [comment]
A similar problem. In the cache, data does not change when you change the localization and call the method withTranslation. It is necessary to pull out the data on all localizations meanwhile. Then I will rewrite the requests.

**Comment by mikebronner** [comment]
Hi @DmitrySkibitsky, please open a new issue for what you are describing. That doesn't sound related at all. I haven't yet considered how translations work in the caching context.

**Comment by DmitrySkibitsky** [comment]
@mikebronner I now have a deep night) I will open the issue tomorrow and describe in detail and lay out the dd collections.

PS Text through the translator. I apologize in advance.

**Comment by shez1983** [comment]
i have come across this problem so i am doing something like: 

```
public function scopeWithPaymentAttempt($q)
    {
        return $q->addSubSelect('last_attempt_id', PaymentAttempt::select('id')
            ->whereRaw('invoice_id = invoices.id')
            ->latest()
        )->with('paymentAttempt');
    }
```

then running it like:

```
 $i = App\Invoice::withPaymentAttempt()->find(1);
```

and i get an error: 

```
BadMethodCallException with message 'Call to undefined method GeneaLabs/LaravelModelCaching/CachedBuilder::addSubSelect()'
```
