### ISSUE TITLE
inRandomOrder return same result

### ISSUE THREAD

**Issue by tradzero** [GeneaLabs/laravel-model-caching#119]
# Issue
when i use `inRandomOrder` to get random result, but i got same result. i know it's may cause by cache. so is it possible to get different result by use some like `shuffle` ? 

## Environment
Laravel Version: *5.6.12*
Laravel Model Caching Package Version: *0.2.52*
PHP Version: *7.2.1*
Homestead Version: not use
Operating System & Version: *mac os 10.12.6*

## Stack Trace
```php
Sponsor::currentSeason()
                ->where('type', Sponsor::TYPE_MEDIA)
                ->inRandomOrder()
                ->first();
```

**Comment by mikebronner** [comment]
Thanks for reporting this. In the mean time you can exclude this from caching by adding `->disableCache()`.

```php
Sponsor::currentSeason()
    ->disableCache()
    ->where('type', Sponsor::TYPE_MEDIA)
    ->inRandomOrder()
    ->first();
```

**Comment by noonanwebgroup** [comment]
We're facing the same issue also. Has there been any progress on a fix for this? Would it help if we created a PR?

**Comment by mikebronner** [comment]
Hi @noonanwebgroup, yes, if you would like to take a stab at creating a PR including unit tests that replicate the issue, that would be great. I can't promise that I will accept the PR sight-unseen, and would have to take some time to review and test it afterwards as well.

Sorry for the delays, I have been swamped with work deadlines this last month.

**Comment by noonanwebgroup** [comment]
Thanks for the swift reply. Of course, it's not a problem. Thanks for the great library. I'll create a PR tomorrow.

**Comment by mikebronner** [comment]
Please try version 0.2.53 or higher, and let me know if that fixes it for you. For now the best solution I was able to find was to disable caching on queries that use `inRandomOrder()`.
