### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by doug7410** [GeneaLabs/laravel-model-caching#126]
Hello,

Is there any way to add support for Laravel 5.4 to this project? It seems to be exactly what I need.

Thanks

**Comment by doug7410** [comment]
@mikebronner Thanks for the response. I bumped down the versions of the dependencies and it seems to be working on 5.4. But like you said, the test setup breaks. 

I'll see if I can get a PR together at some point with the test suite working for 5.4.

Thanks for the awesome package

**Comment by mikebronner** [comment]
@doug7410 Yea, the entire package would have to live in a separate branch, and that's just a nightmare to maintain. I might look into separating the tests out into their own packages, and link to them as sub-repos as needed. That way there could be one core codebase with many test-packages covering different Laravel versions. The key to fixing the tests is changing the dependency versions of the orchestral/testbench packages, we well as PhpUnit and other testing dependencies.

**Comment by doug7410** [comment]
That sounds like a great idea. The core code probably wouldn't change much if any. I'm sure there are lots of laravel < 5.5 projects out there that would benefit from this.

**Comment by mikebronner** [comment]
@doug7410 Good news! I finally figured out a way to test all versions of Laravel without a bunch of overhead and multiple repos or branches. 5.4 compatibility is coming in a few minutes in next release.

**Comment by guestisp** [comment]
Ad support for L5.4 is added, is PHP 7.1 still a requirement or 7.0 would work?

L5.4 works with php 7.0 so you can't really support L5.4 without supporting php 7.0

**Comment by mikebronner** [comment]
Hi @guestisp: I require the latest PHP version for the latest supported Laravel version. This is because I might use PHP features not available in older versions of PHP.

You are welcome to fork the repo and change the PHP requirements to fit your needs, but I can't support that, so you would have to work through any problems on your own.

**Comment by guestisp** [comment]
Forking is ok for me. I'm asking just to know if there are code incompatibilities with PHP 7.0.

As you added compatibility L5.4, I think that PHP 7.0 should work fine, even if not supported by you

Probably, i used the word "support" badly. I meant "is this compatible with PHP 7.0 even without your support ?)

**Comment by mikebronner** [comment]
I may have used PHP 7.1 features, so it might not be compatible. I can't say for sure off the top of my head. My suggestion would be to fork it, then see if all the tests run: `./tests/pu-54.sh`

**Comment by guestisp** [comment]
The only PHP 7.1 used feature is Symmetric array destructuring like:

```
[$cacheCooldown, $invalidatedAt, $savedAt] = $this
            ->getCacheCooldownDetails($instance, $cachePrefix, $modelClassName);
```
by changing that (4-5 occurencies) to the old-style `list` bring back PHP 7.0 compatibility properly

```
list ($cacheCooldown, $invalidatedAt, $savedAt) = $this
            ->getCacheCooldownDetails($instance, $cachePrefix, $modelClassName);
```

**Comment by guestisp** [comment]
I agree, but dropping the whole support to PHP 7.0 only for exactly 5 destructured array it's a pity.....

my 2 cents.

**Comment by mikebronner** [comment]
I'm not willfully not supporting this __because PHP is no longer supported__, rather I am not going to go back and add in support after the fact. If this were a paid product, I would definitely be open to these requests. As a free OSP I have to set limits that I can support in my spare time. Sorry, that's just the reality. I would be happy to discuss paid support options, if you have specific needs and are willing to pay for them to be implemented, I would be happy to do so. :) Not meaning to be snarky, but leaving the door open for anyone using this in client or commercial projects might consider this.
