### ISSUE TITLE
Caching Performance Is Slower Than Database Query

### ISSUE THREAD

**Issue by howya** [GeneaLabs/laravel-model-caching#130]
Apologies for asking a question via the issues.

As above, does this package cache the result of a model query over an intersection table that returns multiple rows? I have a query:

Model->with(relationship)->find(1)->realtionship;

Where relationship is a belongsToMany relationship that is based on another model that also has your package implemented. When testing this with / without cacheing I find that cached is actually much slower (using Redis and MySQL). Would caching be supported in this relationship? If so then I expect it is an issue with my implementation of your package, if not, then I guess it is expected.

Thanks,

Rob

**Comment by mikebronner** [comment]
Hi @howya, thanks for submitting this issue. This looks like it might be related to #127, I'll be looking into this over the weekend.

**Comment by howya** [comment]
Thanks for getting back to me. I'm investigating another approach at the moment. Caching the sql result at the builder. I'm using a hash of the SQL and binding as a key and serialising the SQL result via json_encode. Will be interesting to see the results.

**Comment by mikebronner** [comment]
That's basically what this package does. Can you explain perhaps in more detail what is not working? If you could provide queries you are running that don't provide the expected results, along with any errors, that might help. I'm not sure why this package wouldn't work for you, as it does what you asked in the original question. I'd need more information to be able to help.

**Comment by mikebronner** [comment]
Nevermind my previous comment (deleted).

**Comment by mikebronner** [comment]
@howya I have written a test for this use-case, and am unable to replicate any issues with your query above. It caches everything correctly, as far as I can see. Can you provide more details as to why you think it's not working, as well as add any errors, stack trace, and other eloquent queries so that I can try to replicate the issue.

**Comment by howya** [comment]
OK, give me a few days (it's a holiday here) and I'll take a look. The reason that I believed it not to be working is that it took twice as long to execute a recurring query test (10000 repeated queries for same where clause i.e. same result each time) as the same test with caching removed.

**Comment by howya** [comment]
Hi Mike,

I've put together a very simple example at:

https://github.com/howya/laravel_builder_cache

Just clone it, composer install, then setup the phpunit.xml environment variables to point at your MySQL server and Redis server.

Once setup you can run Composer Test to run a simple performance test. The performance test runs a 1000 iteration loop of query calls (I chose these queries as they are similar to what I require in a project I'm working on). The loop is replicated 3 times:

- Once for queries against Non-Cached 'standard' models
- Once for queries against Builder-Cached models - this is an experimental cache that I'm playing with
- Once for queries against Model-Cached models - this is your package

The test is trivial and does not reflect real world usage as it does not bust the cache and the query domain space is very small i.e. MySql is probably hitting its own cache 100% of the time.

The results I get are:

"Non-Cached time taken: 25.299576044083"
"Builder-Cached time taken: 24.184181928635"
"Model-Cached time taken: 35.246420145035"

I would have assumed that our caching strategies would have been the same or slightly slower than 'Non-Cached' in this test as MySql is probably hitting its own cache 100% of the time. I'm not sure why yours is approx 50% slower. Have I made an error when implementing you caching package?

**Comment by mikebronner** [comment]
@howya  Off the top of my head, this package is more suited to cache complex queries that take a long time to run on their own. That's where the performance improvement lies.

Thanks for putting together a repo, I will play with it and see what's happening. I know that properly configuring redis or memcached can have a large effect on performance.

**Comment by mikebronner** [comment]
Moved this conversation to another issue.
