### ISSUE TITLE
Use database name in cache prefix

### ISSUE THREAD

**Issue by jonagoldman** [GeneaLabs/laravel-model-caching#132]
I see that the database connection name is used as a cache prefix in the [CachePrefixing trait](https://github.com/GeneaLabs/laravel-model-caching/blob/master/src/Traits/CachePrefixing.php).
Is it possible to also add the database name to the prefix?

In a multi tenant application, I have a "main" connection and a "tenant" connection. The database name in the "tenant" connection is changed using a middleware for each tenant. This way I can use the "main" connection for the shared database, and the "tenant" connection for each tenant databases. So adding the database name to the cache prefix will allow me to use model caching without creating one connection per tenant. Related to https://github.com/GeneaLabs/laravel-model-caching/issues/99.

Thanks.

**Comment by mikebronner** [comment]
Yes, we are already doing that; https://github.com/GeneaLabs/laravel-model-caching/blob/master/src/Traits/CachePrefixing.php#L9. Or did you mean something else?

**Comment by jonagoldman** [comment]
@mikebronner I missed that line, I read https://github.com/GeneaLabs/laravel-model-caching/issues/99#issuecomment-376460817 and assumed only the connection name was being used! Thanks!

**Comment by mikebronner** [comment]
Ah yea, it was implemented right after that. :)
