### ISSUE TITLE
Trait method newEloquentBuilder has not been applied, because there are collisions with other trait methods

### ISSUE THREAD

**Issue by eelco2k** [GeneaLabs/laravel-model-caching#137]
# Issue
Trait method newEloquentBuilder has not been applied, because there are collisions with other trait methods on App\Models\Flight.

I found out that i'm also  using \Grimzy\LaravelMysqlSpatial Trait in this model. 
and reading this issue it looks like it has to do with this package. 
[https://github.com/grimzy/laravel-mysql-spatial/issues/17](https://github.com/grimzy/laravel-mysql-spatial/issues/17)

I'm not sure if it's possible to implement a method to fix this issue in this package or that i do have to create my own custom "Illuminate\Database\Eloquent\Builder".

## Environment
Laravel Version: 5.5.40
Laravel Model Caching Package Version: 0.2.62
PHP Version: PHP 7.1.8 

Operating System & Version: Mac OS X

## Stack Trace
```

(1/1) FatalErrorExceptionTrait method newEloquentBuilder has not been applied, because there are collisions with other trait methods on App\Models\Flight
--
```

**Comment by mikebronner** [comment]
Hi @eelco2k, off the top of my head, I believe this is something you will have to resolve locally in your app. Please let me know if you do find a solution, so I can take a look and see if it would be possible to implement in the package.

**Comment by eelco2k** [comment]
as @grimzy commented out in this issue: [https://github.com/grimzy/laravel-mysql-spatial/issues/17](https://github.com/grimzy/laravel-mysql-spatial/issues/17) he wrote a custom Illuminate\Database\Eloquent\Builder and extending own packages classes with a Trait.

Perhaps this would be a good method to do as well for laravel-model-caching.

**Comment by eelco2k** [comment]
i've tried to move the functions in CachedBuilder.php into a Trait but this didn't work sadly. 

I've also tried this in conjuction with the dev-builder-as-trait branch of the grimzy/laravel-mysql-spatial but i'm still getting the same errors.

So no solution yet.

**Comment by mikebronner** [comment]
Yea, I don't think there is an easy solution for this at this time. I'm closing this for now. Please re-open if you have further information that may help out. Thanks for looking into it!

**Comment by Spodnet** [comment]
I had this problem with \Kalnoy\Nestedset\NodeTrait

I think this is working as a simple solution in my case, the node trait ran

```
public function newEloquentBuilder($query) {
    return new QueryBuilder($query);
}
````

Looking at the code in the model caching, it was ok to simply override in my model

```
use \GeneaLabs\LaravelModelCaching\Traits\Cachable {
        \GeneaLabs\LaravelModelCaching\Traits\Cachable::newEloquentBuilder insteadof \Kalnoy\Nestedset\NodeTrait;
}
```

I would imagine providing the trait that's causing issues doesn't do anything that would cause issues overriding might solve it. Otherwise you'll need to write your own trait to handle the conflict cases I would think.

I'm still testing for any side effects...

**Comment by Daniyal-Javani** [comment]
> I had this problem with \Kalnoy\Nestedset\NodeTrait
> 
> I think this is working as a simple solution in my case, the node trait ran
> 
> ```
> public function newEloquentBuilder($query) {
>     return new QueryBuilder($query);
> }
> ```
> Looking at the code in the model caching, it was ok to simply override in my model
> 
> ```
> use \GeneaLabs\LaravelModelCaching\Traits\Cachable {
>         \GeneaLabs\LaravelModelCaching\Traits\Cachable::newEloquentBuilder insteadof \Kalnoy\Nestedset\NodeTrait;
> }
> ```
> I would imagine providing the trait that's causing issues doesn't do anything that would cause issues overriding might solve it. Otherwise you'll need to write your own trait to handle the conflict cases I would think.
> 
> I'm still testing for any side effects...

@Spodnet Have you found any side effects?

**Comment by Spodnet** [comment]
No issues so far :)

**Comment by LiamAird** [comment]
This is still an issue - is there any workaround, now nearly two years later?

**Comment by mikebronner** [comment]
@LiamAird Please open a new issue with full stack trace and query and all the version information.

**Comment by mikebronner** [comment]
@Spodnet @indowebdeveloper @Daniyal-Javani @eelco2k Could you give release 0.10.2 a try and let me know if that fixes the issue? Please see the readme section towards the top regarding conflicting packages as how to implement it. Thanks!

**Comment by LiamAird** [comment]
I tried implementing the fix, but get the error: 
```Call to undefined method GeneaLabs\LaravelModelCaching\ModelCaching::useBuilder()```

```php
use GeneaLabs\LaravelModelCaching\ModelCaching;
use Kalnoy\Nestedset\QueryBuilder;

class AppServiceProvider extends ServiceProvider
{

    public function register()
    {
        //
    }
 
    public function boot()
    {
         ModelCaching::useBuilder(QueryBuilder::class);
    }
```

**Comment by mikebronner** [comment]
Can you make sure you got the latest update, change your composer json to 
```
"genealabs/laravel-model-caching":"^0.10.2",
```

then run `composer update` again.

**Comment by LiamAird** [comment]
@mikebronner Its already at that version. 
![image](https://user-images.githubusercontent.com/11542070/92453486-9b9c9800-f1bf-11ea-9269-3fccb9c017aa.png)

**Comment by mikebronner** [comment]
Hmmm, ok. Leave it at release 0.10.1 for now, I'm working on an update to this functionality and hope to release it in the next day or so.
