### ISSUE TITLE
Question: How to use caching at Vendor packages?

### ISSUE THREAD

**Issue by Nowi5** [GeneaLabs/laravel-model-caching#141]
Dear community,

thank you very much for developing and supporting this model caching package.
As asked already once in the past, is there any nice way to use this package also for vendor packages?
How can I integrate these in Vendor Models e.g. barryvdh/laravel-translation-manager#227 without creating a fork.

Thank you very much for your help.

**Comment by Nowi5** [comment]
Let see if I will be able to adjust all vendor packages so that they allow to overwrite / extend the model via config. Please have a look to https://github.com/barryvdh/laravel-translation-manager/pull/268

**Comment by mikebronner** [comment]
Hi @Nowi5, this is a limitation is most likely out of my hands. If you figure out a way to update this package that fixes this problem, please do submit a PR! :)

**Comment by mikebronner** [comment]
This is probable the same concern as in #137
