### ISSUE TITLE
Too few arguments to function App\Skill::fireModelEvent()

### ISSUE THREAD

**Issue by maurocolella** [GeneaLabs/laravel-model-caching#143]
**Describe the bug**
Caching trait causes crash on complex dynamic relational mappings (many-to-many).

**Eloquent Query**
The query log is not enabled, but the source code is:
https://github.com/maurocolella/__new_me.server/blob/develop/app/Skill.php

**Stack Trace**
<pre><code>
[2018-06-18 05:17:25] local.ERROR: Type error: Too few arguments to function App\Skill::fireModelEvent(), 0 passed in /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 544 and at least 1 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Too few arguments to function App\\Skill::fireModelEvent(), 0 passed in /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 544 and at least 1 expected at /var/www/main/api/vendor/fico7489/laravel-pivot/src/Traits/ExtendFireModelEventTrait.php:14)
[stacktrace]
#0 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(544): App\\Skill->fireModelEvent()
#1 [internal function]: Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#2 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(89): call_user_func(Object(Closure))
#3 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(548): Illuminate\\Database\\Eloquent\\Relations\\Relation::noConstraints(Object(Closure))
#4 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(516): Illuminate\\Database\\Eloquent\\Builder->getRelation('fireModelEvent')
#5 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(496): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'fireModelEvent', Object(Closure))
#6 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(377): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#7 /var/www/main/api/app/Helpers/API.php(92): Illuminate\\Database\\Eloquent\\Model->load('fireModelEvent')
#8 /var/www/main/api/app/Helpers/API.php(59): App\\Helpers\\API->loadRelations(Object(App\\Skill))
#9 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Support/Collection.php(338): App\\Helpers\\API->App\\Helpers\\{closure}(Object(App\\Skill), 0)
#10 /var/www/main/api/app/Helpers/API.php(73): Illuminate\\Support\\Collection->each(Object(Closure))
#11 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): App\\Helpers\\API->marshallDataset(Object(Illuminate\\Database\\Eloquent\\Collection), 'skill')
#12 /var/www/main/api/app/Http/Controllers/SkillController.php(20): Illuminate\\Support\\Facades\\Facade::__callStatic('marshallDataset', Array)
#13 [internal function]: App\\Http\\Controllers\\SkillController->index()
#14 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#15 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#16 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\SkillController), 'index')
#17 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(161): Illuminate\\Routing\\Route->runController()
#18 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(610): Illuminate\\Routing\\Route->run()
#19 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/main/api/app/Http/Middleware/Cors.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Cors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 350)
#28 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(571): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#32 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(549): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#33 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#34 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/main/api/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /var/www/main/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /var/www/main/api/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"} 
</code></pre>

**Environment**
 - PHP: 7.2.0
 - OS: Debian 9 Jessie
 - Laravel: 5.5.*
 - Model Caching: ^0.2.21

**Additional context**
I am trying to load related entities dynamically for presentation according to JSON API (spec).

https://github.com/maurocolella/__new_me.server/blob/develop/app/Helpers/API.php

I tried to add a cacheable trait to the public-facing models (Work, Skill, Article). I tested with Skill above, and it caused the aforementioned error.

**Comment by mikebronner** [comment]
I don't believe this error is related to this package. The namespace LaravelModelCaching is not referenced anywhere in the stack trace. The query being executed in the stack trace is not a cached query. I'm closing this for now, but if you find additional information that suggests it might be this package, please re-open with a new stack trace and eloquent query. :) Thanks!

**Comment by maurocolella** [comment]
My bad, I linked code from the main branch. I assumed it made for an easier explanation.

Here is the same code from the branch that still contains the issue. 

https://github.com/maurocolella/__new_me.server/blob/feature/add-model-caching/app/Skill.php

That bug is in the model caching library. The main branch is active in prod.

I'll gladly log the specific queries, but it is not query-specific. 

It affects this:
`#7 /var/www/main/api/app/Helpers/API.php(92): Illuminate\\Database\\Eloquent\\Model->load('fireModelEvent')`

Eq. Model->load.

https://laravel.com/api/5.5/Illuminate/Database/Eloquent/Model.html#method_load

I think anyone who attempts to load relations actively will be in for a sad time.

**Comment by mikebronner** [comment]
Hmmm, thanks for the update. Could you submit a PR with. Test that recreate this issue?

**Comment by maurocolella** [comment]
Ok. I'll try to make a test case over the weekend.
