### ISSUE TITLE
Caching of global model related data

### ISSUE THREAD

**Issue by getriebesand** [GeneaLabs/laravel-model-caching#144]
Can you implement a function to store data in cache which will be flushed on flushing the models cache?

e.G.:

`MyModel::cacheWithModelTag()->rememberForever('customKey', function(){ return 'data'});`

and when I create a MyModel or delete or flush the cache of MyModel, 'customKey' should be flushed too.

**Comment by mikebronner** [comment]
Intersting idea. Can you elaborate on the use-case for this, perhaps provide a real-world example?

**Comment by mikebronner** [comment]
Closing, as no response received as to what this would be useful for. @getriebesand if you are still interested, please re-open this issue and provide the requested information. Thanks! :)

**Comment by getriebesand** [comment]
I have translations for my models. They are stored in a separate table and will be cached after load.. If I delete the model I want to be sure the translation cache will be deleted too. Or if I update the Model. So I want to call $mymodel->cache()->rememberForever('translations', function(){ return $this->loadTranslations()});

**Comment by mikebronner** [comment]
Hmm, I'm not sure this plugin can support that. This is something you would have to implement on your own to meet your specific app needs. I would look into hooking into the model events `created`, `updated`, `deleted`, and manage your translation cache based on that. Also, it might be beneficial to keep your translation cache in a separate cache store.
On the other hand, if translations are handled automatically (I'm assuming you are using a translation package?) using Eloquent models, and doesn't use its own caching mechanism, then I would think it could work out of the box with no extra work needed.
