### ISSUE TITLE
Add testExistsRelationshipWhereClauseParsing() unit test.

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#15]
Code is already in place, all you need to do is add the test. :)

**Comment by brunorsantos** [comment]
#22

**Comment by brunorsantos** [comment]
Hi! implementing this test, I realized that does not exists an implementation for caching a query for Relationship Absence. It would be when we try to do something like:

`$authors = collect([(new Author)->doesntHave('books')->first()]);`

I tried to execute it, and it returns an error when trying to create a cache key:

ErrorException: Undefined index: column

/home/vagrant/Code/laravel-model-caching/src/CachedBuilder.php:106
/home/vagrant/Code/laravel-model-caching/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1197
/home/vagrant/Code/laravel-model-caching/src/CachedBuilder.php:107
/home/vagrant/Code/laravel-model-caching/src/CachedBuilder.php:28
/home/vagrant/Code/laravel-model-caching/src/CachedBuilder.php:203

Can I open an issue for this?
Thanks

**Comment by mikebronner** [comment]
@brunosantos thanks for reporting, yes, please create an issue! :)
