### ISSUE TITLE
ForgetCache for single Instance

### ISSUE THREAD

**Issue by Nowi5** [GeneaLabs/laravel-model-caching#152]
Hi all,

Sometimes I have DB queries running which are not detected by the Model Caching. For that I would need a function which forget the cache for a single model. E.g. $user->forgetModelCache(); What do you think about that?

Thank you.

**Comment by mikebronner** [comment]
You can call the artisan command to do that:

```php
app("artisan")->call("cache:clear", ["--model" => "App\User"]);
```

You might have to play around with double- or single-backslash, not sure. :) Let me know how that works.

**Comment by Nowi5** [comment]
Yes, but this deletes the cache for all, which is in my case of thousands of users a performance gap. I like just to delete one single instance of a model, not all models.

**Comment by mikebronner** [comment]
No, there is no way to clear the cache for just one instance of a model at this point. Sorry.

**Comment by Nowi5** [comment]
I know, question is if we should have a look into. Any idea where to best start when looking into PR?

**Comment by mikebronner** [comment]
@Nowi5 What I'm saying is that it's not possible with how the cache is set up. If you want to have a stab at creating a PR, by all means, but I'm sure you will find that it won't work without rewriting the caching logic completely. :)
