### ISSUE TITLE
Problem with php 7.2.8

### ISSUE THREAD

**Issue by folkevil** [GeneaLabs/laravel-model-caching#155]
**Describe the bug**
I've installed laravel-model-caching, but my app got this error after install 

![PHP error](https://i.imgur.com/yZycqYM.png)

**Environment**
 - PHP: 7.2.8
 - OS: Ubuntu 16.04
 - Laravel: 5.6
 - Model Caching: latest

**Comment by mikebronner** [comment]
Please provide the full stack trace, as well as the exact version of the package ("latest" isn't very helpful, as versions can be changing from day to day). Thanks!

**Comment by mikebronner** [comment]
@folkevil I am unable to replicate this issue. Your error leads me to believe you are actually running  an earlier version of PHP (< 7.1), which is where array restructuring was introduced.

**Comment by mikebronner** [comment]
Closing this for now due to inactivity. Please re-open with additional information if you are still experiencing this problem.
