### ISSUE TITLE
Cached relationships not invalidated, even if caching is off

### ISSUE THREAD

**Issue by denitsa-cm** [GeneaLabs/laravel-model-caching#158]
**Describe the bug**

Model relations are not re-fetched from the database during a foreach loop. 

That happens even if my cache driver is set to array `CACHE_DRIVER=array` (which I would assume should not do any caching).

**Eloquent Query**

Within a loop I do:

```
//loop start
       $subscriptionPeriod->vendor()->associate($vendor)
            ->publisher()->associate($publisher)
            ->status()->associate($status)
            ->subscription()->associate($subscription)
            ->save();

       $latestSubscriptionPeriod = $subscription->subscriptionPeriods()->orderBy('replaces_subscription_period_id', 'desc')->first();
//loop end
```

I expect that $latestSubscriptionPeriod is going to be updated on the next iteration of the loop, but it is not. 

However, it is updated successfully if I disable caching by removing the `Cacheable` trait from my models.

My subscription has the following relation to periods: 

```
    /**
     * Get all of the subscriptions in the group.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subscriptionPeriods()
    {
        return $this->hasMany(SubscriptionPeriod::class, 'subscription_id', 'id');
    }
```

**Stack Trace**

//

**Environment**
 - PHP: 7.2.4
 - OS: Ubuntu 18.04
 - Laravel: 5.6.33
 - Model Caching: 0.2.64

**Comment by denitsa-cm** [comment]
@mikebronner That seems to work! Thanks! :) But it is not the intended behavior, right? :) 

Also, I might have misunderstood, but is it intended that the models are still cached even if the `CACHE_DRIVER = array`?

P.S. All my models extend from a Base that uses your `Cacheable` trait. Thank you for it! :)

**Comment by denitsa-cm** [comment]
@mikebronner I thought it fixed it but I had just forgotten to remove the commented out `Cachable` trait. 

It doesn't fix it, unfortunately 🤔 

All my models extend from a Base that uses your trait :) Is there any other code I can paste that will help maybe? 

Thank you for the package, by the way! :)

**Comment by mikebronner** [comment]
@denitsa-cm 
First: please retest using the latest release from today or later.
Second: If the issue persists, can you provide the entire model code for the model that is exhibiting this problem, as well as the entire code around the query where the problem occurs (including code for loops and fetching of data).

**Comment by denitsa-cm** [comment]
@mikebronner will do, thanks

**Comment by mikebronner** [comment]
Closing this for now due to inactivity. Please re-open with additional information if you are still experiencing this problem.

**Comment by mikebronner** [comment]
Will look into this and see if I can replicate it.

**Comment by mikebronner** [comment]
@denitsa-cm  After researching it a bit, I believe the problem is down to the relationship. Queries run off relationships are not cached, so relationships should only be used passively. Instead of creating a complex relationship to return the latest subscription period (which really might not be considered a relationship, but an attribute), I would recommend this:

```php
    public function getLatestSubscriptionPeriodAttribute()
    {
        return $this
            ->subscriptionPeriods()
            ->latest("id")
            ->first();
    }
```

That does work as intended in caching.

**Comment by denitsa-cm** [comment]
@mikebronner Thank you for the suggestion. I would like to keep it as a relation because I often need to load it but will add it as an attribute as well and see how that works. 

Unfortunately, I bumped into another issue https://github.com/laravel/telescope/issues/187 so have to deal with that first. :)
