### ISSUE TITLE
Name "Cachable" should be "Cacheable"

### ISSUE THREAD

**Issue by pedzed** [GeneaLabs/laravel-model-caching#159]
I was trying to include `Cacheable`, but it was not found. Apparently it is mistakenly called `Cachable`.

File: [src/Traits/Cachable](https://github.com/GeneaLabs/laravel-model-caching/blob/585880021c85a660fb420bbbe242bbe332013670/src/Traits/Cachable.php)

**Comment by mikebronner** [comment]
Doh! I will update this with the next breaking update.

**Comment by mikebronner** [comment]
Further research suggest this is the correct spelling: https://howtospell.co.uk/droptheerule.php

Keeping `Cachable`.

**Comment by pedzed** [comment]
I am not sure how you conclude from the text that "it is the correct spelling". Can you clarify?

![image](https://user-images.githubusercontent.com/8146593/46853073-60d82c80-cdfd-11e8-8dcd-dcd795d7767a.png)

![image](https://user-images.githubusercontent.com/8146593/46853117-8107eb80-cdfd-11e8-89b3-2d47497bf29e.png)

![image](https://user-images.githubusercontent.com/8146593/46853148-941abb80-cdfd-11e8-8c4f-134913ca299a.png)

- "cachable" gives "About 125,000 results"
- "cacheable" gives "About 905,000 results"

Cachable might be a valid alternative spelling, but the general accepted spelling is clearly "cacheable".

**Comment by szepeviktor** [comment]
The framework goes the other way:
https://github.com/search?q=repo%3Alaravel%2Fframework%20Cacheable&type=code
