### ISSUE TITLE
Pagination in the query is not working properly. 

### ISSUE THREAD

**Issue by NishantSoni** [GeneaLabs/laravel-model-caching#160]
I am applying pagination in the query dynamically. Like this - 
```php
public function applyPagination($request, $queryBuilder)
{
	if($request->has('page') && $request->has('count')) {

		$limit = $request->get('count')

		$queryBuilder->paginate($limit)
	}
}
```

some thing like in this way i am working. 

First time pagination is applied and returns the result properly.  But in the second call of this method pagination is not working (because only pagination part is cached, so does not work in second time, third time and so on)... how should i fix this issue, any suggestion please?

**Comment by mikebronner** [comment]
Pagination has been implemented and tested. See if the unit tests help with your use-case: 
https://github.com/GeneaLabs/laravel-model-caching/blob/master/tests/Integration/CachedBuilder/PaginateTest.php

My guess would be that the $queryBuilder being passed in is not a CachedBuilder, which would cause the problem you are having.

**Comment by mikebronner** [comment]
@NishantSoni Please provide an update for this issue. Are you still having it? If so, please provide the full query and relevant code, or link to a repo with the problem.

**Comment by mikebronner** [comment]
Closing this for now due to inactivity. Please re-open with additional information if you are still experiencing this problem.

**Comment by NishantSoni** [comment]
Yes sure , this must be closed, actually eloquent events was not fired, due to this there was some issue in the model-caching , and I have fixed this in my code. Thanks & really sorry for late reply.

**Comment by mikebronner** [comment]
@NishantSoni glad to hear you got it resolved :)
