### ISSUE TITLE
Model::forcedelete();

### ISSUE THREAD

**Issue by prmdeveloper** [GeneaLabs/laravel-model-caching#162]
**Describe the bug**
When using the (forcedelete) function, the cache is not being cleared.

**Eloquent Query**
```php
 ContractItemAsset::where('id_contract_item', $idContractItemCurrent)->forcedelete();
```
**Environment**
 - PHP: [e.g. 7.1.0]
 - OS: [e.g. Centos 7]
 - Laravel: [e.g. 5.6.23]
 - Model Caching: [e.g. 0.2.58]

**Comment by mikebronner** [comment]
@prmdeveloper Thanks for reporting this. I will try to add a unit test and code to account for this. Might be a bit though.
