### ISSUE TITLE
do it support this ?

### ISSUE THREAD

**Issue by vahidalvandi** [GeneaLabs/laravel-model-caching#166]
$data['rows']= accounts_detailed::join('accounting_accounts_detailed_group', 'accounting_accounts_detailed_group.id', '=', 'accounting_accounts_detailed.group_id')
         ->paginate(15, array('accounting_accounts_detailed.*'));

**Comment by mikebronner** [comment]
You will need to provide more information for me to be able to answer your question. Is `accounts_detailed` an instance of a `Cachable` Model? (Normally it would be written `AccountsDetailed::join()`.)

Joins __should be__ supported, but if you have issues, please open a new issue. (I didn't see a unit test specifically for joins, and I am not in the office for a few more days, so it's a bit hard for me to check.)

**Comment by vahidalvandi** [comment]
yes all table use trade Cachable
