### ISSUE TITLE
add support file cache driver

### ISSUE THREAD

**Issue by nazaninhesari** [GeneaLabs/laravel-model-caching#167]
do it   support file cache driver ?

**Comment by mikebronner** [comment]
You can use file caching, but it will be degraded support, since file cache does not support tags.

**Comment by Yannik-Slym** [comment]
@mikebronner 

Hello :) 

File driver can work with cache tags with package like this one https://github.com/swayok/alternative-laravel-cache.

Maybe add in readme ?

**Comment by mikebronner** [comment]
I believe file driver now supports cache natively. I will have to add tests, but it should work without any additional packages. I have updated the readme with a drivers section that shows which drivers are and are not supported.

**Comment by mikebronner** [comment]
#300

**Comment by Yannik-Slym** [comment]
@mikebronner No file is not a TaggableStore natively ( https://github.com/laravel/framework/blob/6.x/src/Illuminate/Cache/FileStore.php ).

**Comment by mikebronner** [comment]
@Yannik-Slym That's odd ... I was looking at FileStore just the other day, and it was clearly marked Taggable. I will have to retrace my steps and figure out which one that was.

**Comment by mikebronner** [comment]
Bummer, you're right. Fixing documentation now.
