### ISSUE TITLE
PHP 7.1.1.

### ISSUE THREAD

**Issue by renege** [GeneaLabs/laravel-model-caching#168]
Hello, what is the reason that PHP 7.1.3 is the minimal requirements. I want to run it on a PHP 7.1.1 server which I can't update myself to a new PHP-version. Is it really needed to run PHP 7.1.3 because of added functions, or can you downgrade it in the composer.json?

**Comment by mikebronner** [comment]
Hi @renege Please see #71 for an explanation.
