### ISSUE TITLE
Using detach() Laravel 5.4

### ISSUE THREAD

**Issue by Dcuevac93** [GeneaLabs/laravel-model-caching#169]
**Bug**
Problems when using `detach()` on my models.

**Basically I found this bug**

The problem is that here -> `fico7489/laravel-pivot/src/Traits/FiresPivotEventsTrait.php(39)`
Are using this function `qualifyColumn()` which is not available in Laravel 5.4.

https://laravel.com/api/5.4/Illuminate/Database/Eloquent/Model.html
https://laravel.com/api/5.5/Illuminate/Database/Eloquent/Model.html

**Eloquent Query**
```php
$model->related_model()->detach();
```

**Stack Trace**
Call to undefined method Illuminate\Database\Query\Builder::qualifyColumn();
fico7489/laravel-pivot/src/Traits/FiresPivotEventsTrait.php(39);

**Environment**
 - PHP: [7.1.20]
 - OS: [Debian GNU/Linux 9]
 - Laravel: [5.4]
 - Model Caching: [0.2.64]

**Additional context**
I know this library `fico7489/laravel-pivot` is not developed by you but you have it on your composer.json `"fico7489/laravel-pivot": "*"`. I would like to keep using this library and I can't upgrade my Laravel version right now.

**Comment by mikebronner** [comment]
@Dcuevac93 Thanks for reporting this. I will look into and see if I can replicate the problem in the unit tests.

**Comment by mikebronner** [comment]
Hi @Dcuevac93, unfortunately there is nothing I can do to fix this issue. `laravel-pivot` is no longer actively supported for Laravel 5.4, so the only solution would be for you to upgrade your app's Laravel version. I'm going to have to close this, unfortunately. Sorry.
