### ISSUE TITLE
Class not found in cache clear 

### ISSUE THREAD

**Issue by nagendraK6** [GeneaLabs/laravel-model-caching#170]
**Describe the bug**
My model (Tag) is inside a folder Model. 
So to clear the cache i am calling 
php artisan modelCache:clear --model=App\Model\Tag;

**Eloquent Query**
Please provide the complete eloquent query that caused the bug, for example:
```php
$model->with('otherModel')->get();
```

**Stack Trace**
Hitting exception
  Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'AppModelTag' not found

  at /var/www/html/web/www/vendor/genealabs/laravel-model-caching/src/Console/Commands/Clear.php:35
    31|     }
    32|
    33|     protected function flushModelCache(string $option) : int
    34|     {
  > 35|         $model = new $option;
    36|         $usesCachableTrait = $this->getAllTraitsUsedByClass($option)
    37|             ->contains("GeneaLabs\LaravelModelCaching\Traits\Cachable");
    38|
    39|         if (! $usesCachableTrait) {

  Exception trace:

  1   GeneaLabs\LaravelModelCaching\Console\Commands\Clear::flushModelCache("AppModelTag")
      /var/www/html/web/www/vendor/genealabs/laravel-model-caching/src/Console/Commands/Clear.php:19

  2   GeneaLabs\LaravelModelCaching\Console\Commands\Clear::handle()
      /var/www/html/web/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
**Environment**

 - PHP: [e.g. 7.1.0]
 - OS: [e.g. Ubuntu 18.04]
 - Laravel: [e.g. 5.7]
 - Model Caching: Redis

**Additional context**

**Comment by mikebronner** [comment]
@nagendraK6 try entering the command like this:
```
php artisan modelCache:clear --model=\\App\\Model\\Tag
```

That should be the correct format. Let me know if that doesn't work.

**Comment by mikebronner** [comment]
Closing this for now. If you still have the issue, please reopen.
