### ISSUE TITLE
Issue with paginate function

### ISSUE THREAD

**Issue by IlyaBerzin** [GeneaLabs/laravel-model-caching#172]
Your lib has some bug in 
laravel-model-caching/src/CachedBuilder.php file in function paginate()

Param pageName has default value - "page", and in line 129 
$page = request("page", $page ?: 1);
you must use this variable like this:
$page = request($pageName , $page ?: 1);

At the moment there is no possibility to use a page name other than the "page".

Pls fix it. Thanks.

**Comment by mikebronner** [comment]
@IlyaBerzin Feel free to submit a PR, I won't be able to get to this for another week or two. Thanks for submitting the issue.

**Comment by mikebronner** [comment]
Working on this now. Currently blocked by issues in unit test framework:
https://github.com/orchestral/testbench-browser-kit/issues/7
