### ISSUE TITLE
Flush cache from model's static function

### ISSUE THREAD

**Issue by andersonpem** [GeneaLabs/laravel-model-caching#174]
**Describe the solution you'd like**
It would be interesting to flush a model's cache from its class. Then, if I did an action that requires the cache to be flushed and I'm not sure if it was in fact flushed I would go like:
`Model::ClearCache()` 

**Describe alternatives you've considered**
I considered building the function in the Model, but I'm facing some issues to call an Artisan command to do that.

Sorry if I seem to be a little beginner.
Thank you for the great package. :)

**Comment by mikebronner** [comment]
@andersonpem Is there a specific use-case you are looking for that the package currently doesn't do? It is not necessary to manually flush the cache for a model, as it is done automatically. Are there instances where that doesn't work for you?

**Comment by andersonpem** [comment]
I agree with you. It's supposed to be handled automatically. I'll close the issue :)
