### ISSUE TITLE
Ability to remember for X minutes?

### ISSUE THREAD

**Issue by dmason30** [GeneaLabs/laravel-model-caching#175]
**Describe the solution you'd like**
Pretty self explanatory, I have some Models that I may not want to be remembered "forever" it would be good if we could specify the expiry minutes at Model level?

**Comment by mikebronner** [comment]
Let me ask you why you wouldn't want that? The invalidation routines should make it irrelevant if it is saved forever or not. Could you explain your use-case a bit more?

**Comment by dmason30** [comment]
I have some nightly raw queries (CRUD) not using the Model directly due to their complex nature and requirement to be optimised for speed. Although I have just noticed that I could access the `Model` class and call the `flushCache` method.. apologies I will close this..

**Comment by mikebronner** [comment]
Sounds good. You can also flush the cache from the command line, so you could trigger that if you wanted from a script run from a CRON job.

**Comment by mikebronner** [comment]
@atodd Unfortunately the way invalidation works is that it always flushes the cache for the models involved in any update, insert, or delete queries. There really is no way around that.
