### ISSUE TITLE
how to clean cache only when data changes

### ISSUE THREAD

**Issue by guangdao428** [GeneaLabs/laravel-model-caching#178]
hi, i have two projects, front and admin, front to C and admin to B. front C use cache fully, but data in B
often changes , so only want to clean cache where data changes in B, and query request in B do't use cache.skip the package, i don't know how to resolve it . please hope your reply. thanks.

**Comment by guangdao428** [comment]
thanks for your reply

yes i have 2 projects, but all of them use caching.2 projects share cached data.one can use caching data and update caching data.the another one hope only updating caching data, so that all data in cache changes.

hope your answer.

**Comment by mikebronner** [comment]
@guangdao428 Sorry, that scenario is not supported. The cache can only be updated from the same project.
