### ISSUE TITLE
Should eager loaded nested (polymorphic) relations get cleared on update?

### ISSUE THREAD

**Issue by dmason30** [GeneaLabs/laravel-model-caching#179]
This is more of a question, as I am probably using this library in an unusual way.

I am experiencing an issue where I am updating a model but when I eager load it via another model it seems to be getting an unchanged version from the cache. 

So on a query I am eager loading the relations like so:
```
Currency::with(['setting', 'setting.trackable'])....
```
**Currency Model**
This is using the `Cachable` trait.

The `setting` relation:
```
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function setting()
    {
        return $this->hasOne(Setting::class, 'id', 'settings_id');
    }
```

**Setting Model**
This is **NOT** using the `Cachable` trait due to https://github.com/GeneaLabs/laravel-model-caching/issues/176 and this table has a json column. 

The `trackable` relation:
```
    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function trackable()
    {
        return $this->morphTo();
    }
```

**`trackable` Models**
These are using the `Cachable` trait.

**Issue**
I have a form that contains fields for both `Setting` and the related `trackable` model so when it is submitted it makes changes to both models. if I then make the same query as above the `trackable` relation returns a cached version without the changes.
```
Currency::with(['setting', 'setting.trackable'])....
```

Is this because the `Setting` model is NOT using caching?

**Environment**
 - PHP: 7.1.20
 - OS: Ubuntu 14.04
 - Laravel: 5.6.*
 - Model Caching: 0.3.1

**Comment by guangdao428** [comment]
need to use all models.

**Comment by mikebronner** [comment]
@dmason30 Yes, @guangdao428 is correct. If you don't use catchable on all models affected in your query, you will get unexpected results, due to their cache not being flushed. I'm looking into #176 now, and hope to have that resolved soon.
