### ISSUE TITLE
Is caching database or query?

### ISSUE THREAD

**Issue by mrahmadt** [GeneaLabs/laravel-model-caching#181]
Hello

Sorry for this silly question, but does this module cache all select queries or it actually cache the database table into redis ?

What about insert and update operations, will these operation update the cache?

I would love to know how does it work, the readme file is ok but no explanation 
Thanks

**Comment by mikebronner** [comment]
Hi @mrahmadt, this package only caches query results, not the database itself. Insert and updates clear the cache for the affected models, then recreate the cache the next time a query is run, so the cache will remain correct for all operations. In the readme it says that it is self-invalidating, which is what that means.
