### ISSUE TITLE
Not caching to the right database 

### ISSUE THREAD

**Issue by mrahmadt** [GeneaLabs/laravel-model-caching#182]
Hi

So I configured MODEL_CACHE_STOR in my .env to point to redis with different database/index number that the one I use in my cache but i think its still using my default cache database

Am I using it right?

Thanks

**Comment by mikebronner** [comment]
Keep in mind that you will have to create a configuration for the other cache store in your cache and database config files. If you are still having issues after doing that, please re-open and post your database and cache config files. Also make sure that you're `.env` file has `MODEL_CACHE_STORE`, and not `MODEL_CACHE_STOR` (was probably a typo in the description above, but I just want to make sure).

**Comment by mrahmadt** [comment]
Thank @mikebronner 

I did create configuration for my other cache store, here is my file:

.env
`
    MODEL_CACHE_STORE=modelcache
`

cache.php
`
     'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
        ],
        'modelcache' =>[
            'driver' => 'redis',
            'connection' => 'modelcache',
        ],
`

database.php
`
          'cache' => [
        'host' => env('REDIS_HOST', 'localhost'),
        'password' => env('REDIS_PASSWORD', null),
        'port' => env('REDIS_PORT', 6379),
        'database' => 1,
        'read_timeout' => 60,
        'timeout' => 5,
        'persistent' => false
      ],
      'modelcache' => [
        'host' => env('REDIS_HOST', 'localhost'),
        'password' => env('REDIS_PASSWORD', null),
        'port' => env('REDIS_PORT', 6379),
        'database' => 2,
        'read_timeout' => 60,
        'timeout' => 5,
        'persistent' => false
      ],
`

**Comment by mikebronner** [comment]
Did you clear your config cache? `php artisan config:clear`? It's probably cached there.
