### ISSUE TITLE
increment() and decrement() do not invalidate cache

### ISSUE THREAD

**Issue by booni3** [GeneaLabs/laravel-model-caching#184]
Using the built in decrement/increment functions does not invalidate the cache.

**Eloquent Query**
```php
// Does not invalidate cache
$this->increment('qty_available', $qty);
```

```php
// Invalidates Cache
$this->qty_available = $this->qty_available + $qty;
$this->save();
```

**Additional context**
Maybe this is not intended behaviour of the package? Should it just be the update/save methods that work with cache invalidation?

On a side note, while caching does seem to be doing something on my development/homestead environment, it does not seem to behave in the same was as production. Dev is using file cache driver while production is using redis.

**Comment by mikebronner** [comment]
@booni3 Thanks for the catch on `increment()` and `decrement()` .... I will add those in.

This package is not really optimized for use with file or array cache drivers. If you notice any problems on production, please open a new issue with the specifics there.

Thanks! :)

**Comment by mikebronner** [comment]
@booni3 Thanks for being patient with this. This should now work correctly after release 0.3.6. :)
