### ISSUE TITLE
Single database multi-tennant setup - cache prefix and self-invalidation

### ISSUE THREAD

**Issue by booni3** [GeneaLabs/laravel-model-caching#187]
This is maybe more of a question as I expect it may have been considered already. If not, a feature request!

I have a single database, multi-tennant application consisting of a single master admin account (that can view all data, make changes etc.) and then multiple tenants. The tenant is defined by an account_id column on each applicable table

The master admin account will be making changes to the tenants, as will the tenants.

I originally setup as suggested in readme:

```
if(\Auth::user()->isAdmin()){
    config(['laravel-model-caching.cache-prefix' => 'admin']);
} else {
    config(['laravel-model-caching.cache-prefix' => \Auth::user()->account_id]);
}
```
However, with this when the master account made a change on the model, the cache was not invalidated fo the tenants. 

As in a multi-tenant application, each model is generally owned by a tenant. I would love to be able to key the cache to the model owner (in my case each multi-tenant model has the field `account_id`).

```
class Order extends Model
{
    public function __construct(array $attributes = [])
    {
        config(['laravel-model-caching.cache-prefix' => $this->account_id]);
        parent::__construct($attributes);
    }
}
```

However, in the model constructor the attributes of the model are not available. Can anyone see any work around to this?

**Comment by mikebronner** [comment]
@booni3 There should be nothing you need to do, not even set up the prefix. If your query includes a where clause to restrict to the respective tenant, it will cache different results for different tenants.

Have you confirmed that using Model Caching for Laravel returns unexpected results without using the manual prefix setting?

**Comment by mikebronner** [comment]
Closing this for now. Please reopen if issue persists.

**Comment by booni3** [comment]
@mikebronner sorry for the delay getting back on this. My app was running OK without caching so I thought I would just leave this out, but now I do want to try and revisit. This package is great and I would love to be able to use it across our apps (many have a similar architecture to below).

I believe my problem may be caused due to a mix of multi-tennant users but also additional interaction from admin which is not restricted to the tennant_id's.

For example:

Tenant Query
```
SELECT * FROM ORDERS WHERE ORDER ID = '1234' AND tenant_id = '1234'
```

Admin Query
```
SELECT * FROM ORDERS WHERE ORDER ID = '1234'
```

The tenant_id WHERE in my case is turned on/off via middleware, depending on who is logged in. It is present in every/all types of query.

The problem I was having before, was an admin would modify an order and it would invalidate their cache, but if you then logged in as the user and viewed the same database entry, the cache had not been invalidated and it was sill showing the old version.

I am not sure if there is any way around this?
