### ISSUE TITLE
Multiple Connection Database (Sub Connection) Cache No Function 

### ISSUE THREAD

**Issue by bluevyjohn** [GeneaLabs/laravel-model-caching#191]
@mikebronner 
Multiple Connection Database (Sub Connection) Cache No Function 

I have follow your instruction, but for model those connect sub connection , create, update,delete the cache still is no updated, it keep maintain old 1... 

for example:
```php
use GeneaLabs\LaravelModelCaching\Traits\Cachable;
class Companies extends Model
{
    use Cachable;
    public function __construct($attributes = [])
    {
        config(['laravel-model-caching.cache-prefix' => 'seconddb']);

        parent::__construct($attributes);
    }
    //use global connection database
    protected $connection= 'seconddb';

    protected $dates = ['deleted_at'];

    protected $table = 'companies';

    protected $guarded  = ['id'];
}
```

**Environment**
 - PHP: [e.g. 7.1.0]
 - Laravel: [e.g. 5.4]
 - Model Caching: [e.g. 0.3.3]

**Additional context**

**Comment by mikebronner** [comment]
Closing this for now. Please re-open if this issue persists.
