### ISSUE TITLE
Invalidate Cache after bulk insert

### ISSUE THREAD

**Issue by mrahmadt** [GeneaLabs/laravel-model-caching#194]
Hello

In my project I have to insert bulk data to a database table (100 to 400 records) per app user, I use raw SQL with DB:insert() to do the insert (I want to have the insert as fas as possible)

Now the issue is after the bulk insert I'm not able to Invalidate the cache to get the new records.

**Comment by mikebronner** [comment]
I will look into this over the next few days. In the meanwhile you can execute the artisan command from you code:

```php
artisan()->call("model-cache:clear", ["--model" => <ModelName>::class]);
```

**Comment by mrahmadt** [comment]
Many Thanks

**Comment by mikebronner** [comment]
Also, if you use the insert command on the model, instead of the `DB` Facade, it should invalidate the cache.

**Comment by mikebronner** [comment]
@mrahmadt Ah! never mind, I already had the functionality included:

```php
$model->flushCache();
```

It slipped my mind. Sorry.
