### ISSUE TITLE
GlobalScope conditional where for Multi Tenants

### ISSUE THREAD

**Issue by maicolbruski** [GeneaLabs/laravel-model-caching#199]
**Describe the bug**

Hi, i use `addGlobalScope` for all `query gets` on my application, but  not change the cache when i changing $shopId = 1 to $shopId = 2.
Its possible?
Or what your opinion for this situation?
This is best way for a multi-tenant, or add a `where` in `Model` only its better?

Tks!

**Eloquent Query**
A number 1 is a my tenant 1. my application have a one DB mysql, for X shopId (tenants).

```php
static::addGlobalScope('selectShopId', function (Builder $builder) {
   $tenant = 1;
   $builder->where('shop_id', $tenant);
});
```

**Stack Trace**
The full stack trace from your log file.

**Environment**
 - PHP: 7.2
 - OS: mac
 - Laravel: 5.7
 - Model Caching: latest

**Additional context**

**Comment by mikebronner** [comment]
Unfortunately global scopes are currently not supported for caching. :( This is something I plan to evaluate possible solutions for in the future, but so far have not found a solution for, yet.

**Comment by mikebronner** [comment]
@maicolbruski I believe global scopes are now working. If you're interested, I would love to hear if the package is working for you now. Please test with release 0.8.4 or newer, if you do. Thanks!

**Comment by maicolbruski** [comment]
Hi @mikebronner, Perfect!!! I will do some tests and then let you know
