### ISSUE TITLE
Question: How many cache records should be created when using firstOrFail?

### ISSUE THREAD

**Issue by shawnheide** [GeneaLabs/laravel-model-caching#201]
# Issue
In looking at the cache records in Redis from a single call of `firstOrFail` I see three records created and am wondering if this is the intended behavior. It's probably just easier to follow if you set a breakpoint in the [(`get` method)](https://github.com/GeneaLabs/laravel-model-caching/blob/7be8044842e7bf626a4ff5f916a1f5432b287ce6/src/CachedBuilder.php#L94) of CachedBuilder and go through the stack, but I'll try to summarize what I'm seeing. 
- the first record is from the `find` method in CachedBuilder
- the next is from the `first` method in CachedBuilder which gets called from the parent call to Illuminate\Database\Eloquent\Builder to `find`
- the last record is for the `get` method in CachedBuilder which gets called from the parent call to Builder in the BuildsQueries trait's `first` method which uses `take(1)`. The call to `take(1)` also sets the `limit` property to true which turns the result into a collection

So what I end up with are two (almost identical) cache records for the model and one for a collection with one element. Is that how it's supposed to be or am I missing something in understanding all of this? Thanks for your time and help, I really appreciate it. 

## Environment
Laravel Version: 5.6.39
Laravel Model Caching Package Version: 0.3.6
PHP Version: 7.2.2

## Stack Trace
```
GeneaLabs\LaravelModelCaching\CachedBuilder->get (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:94)
GeneaLabs\LaravelModelCaching\CachedBuilder->first (/var/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:77)
GeneaLabs\LaravelModelCaching\CachedBuilder->GeneaLabs\LaravelModelCaching\{closure} (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:286)
Illuminate\Cache\RedisTaggedCache->rememberForever (/var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:362)
GeneaLabs\LaravelModelCaching\CachedBuilder->retrieveCachedValue (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:288)
GeneaLabs\LaravelModelCaching\CachedBuilder->cachedValue (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:233)
GeneaLabs\LaravelModelCaching\CachedBuilder->first (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:77)
GeneaLabs\LaravelModelCaching\CachedBuilder->find (/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:291)
GeneaLabs\LaravelModelCaching\CachedBuilder->GeneaLabs\LaravelModelCaching\{closure} (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:286)
Illuminate\Cache\RedisTaggedCache->rememberForever (/var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:362)
GeneaLabs\LaravelModelCaching\CachedBuilder->retrieveCachedValue (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:288)
GeneaLabs\LaravelModelCaching\CachedBuilder->cachedValue (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:233)
GeneaLabs\LaravelModelCaching\CachedBuilder->find (/var/www/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:66)
GeneaLabs\LaravelModelCaching\CachedBuilder->findOrFail (/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:321)
App\TestModel->__call (/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1570)
App\TestModel->findOrFail (/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1582)
Illuminate\Database\Eloquent\Model::__callStatic (/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1582)
Illuminate\Database\Eloquent\Model::findOrFail (/var/www/app/Http/Controllers/TestController.php:17)
...
```

**Comment by mikebronner** [comment]
Hi @shawnheide, this sounds like intended behavior. This package caches any queries that Eloquent runs behind the scenes. If Laravel runs multiple queries for `->find()`, then it will cache the results of each of those. Sorry for the late reply.
