### ISSUE TITLE
Getting error while update item

### ISSUE THREAD

**Issue by anilgangani04** [GeneaLabs/laravel-model-caching#202]
**Describe the bug**
I am getting error as below while update Item object...

[2019-01-17 08:34:58] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to App\Models\App\Item::App\Models\App\{closure}() must be an instance of App\Models\App\Builder, instance of GeneaLabs\LaravelModelCaching\CachedBuilder given, called in /home/anilg/data1/html/****/vendor/illuminate/database/Eloquent/Builder.php on line 921 in /home/anilg/data1/html/****/app/Models/App/Item.php:139
Stack trace:
#0 /home/anilg/data1/html/****/vendor/illuminate/database/Eloquent/Builder.php(921): App\Models\App\Item::App\Models\App\{closure}(Object(GeneaLabs\LaravelModelCaching\CachedBuilder))

Item Model has below additional code : 

protected static function boot()
    {
        parent::boot();

        # Order by order DESC
        static::created(function() {
            Artisan::call('cache:clear');
        });

        static::updated(function() {
            Artisan::call('cache:clear');
        });

        static::deleted(function() {
            Artisan::call('cache:clear');
        });

        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('order', 'asc');
        });
    }

**Environment**
 - PHP: [7.1.26]
 - OS: [Ubuntu 18.04]
 - Laravel: [Laravel Framework Lumen (5.6.4) (Laravel Components 5.6.*)]
 - Model Caching: [0.3.4]

**Additional context**
If I clear cache by command "php artisan cache clear" then It's working well for only first time.

**Comment by mikebronner** [comment]
Thanks for posting this. Can you provide the full stack trace of the error? That will help me identify what is going on.

**Comment by mycarrysun** [comment]
remove the class `Builder` from the line that says:
```
static::addGlobalScope('order', function (Builder $builder) {
```

**Comment by mikebronner** [comment]
Thanks @mycarrysun :). I was hoping to find out what actually is passing in the closure to cause this issue. If a builder object is not being passed in, I would expect it to fail further down the line. My hunch is that something might be set up wrong with dependency injection?

**Comment by mycarrysun** [comment]
@mikebronner if he wants to keep the class, he can just use:
```php
// App\Models\App\Item.php
protected static function boot()
{
    parent::boot();

    # Order by order DESC
    static::created(function() {
        Artisan::call('cache:clear');
    });

    static::updated(function() {
        Artisan::call('cache:clear');
    });

    static::deleted(function() {
        Artisan::call('cache:clear');
    });

    static::addGlobalScope('order', function (Illuminate\Database\Eloquent\Builder $builder) {
        $builder->orderBy('order', 'asc');
    });
}
```

The error will go away. This is not a bug with the library.

**Comment by anilgangani04** [comment]
Thanks guys

**Comment by mikebronner** [comment]
@mycarrysun I will research your solution to see if it solves the global scope problems #106
