### ISSUE TITLE
 Installation request for genealabs/laravel-model-caching ^0.3.6 

### ISSUE THREAD

**Issue by mahmod2000** [GeneaLabs/laravel-model-caching#205]
Hi,

**Describe the bug**
When I want to install the Model caching package, it throws the following error:
 Problem 1
    - Installation request for genealabs/laravel-model-caching ^0.3.6 -> satisfiable by genealabs/laravel-model-caching[0.3.6].
    - genealabs/laravel-model-caching 0.3.6 requires fico7489/laravel-pivot dev-new@dev -> satisfiable by fico7489/laravel-pivot[dev-new] but these conflict with your requirements or minimum-stability.

**Environment**
 - PHP: 7.2
 - OS: Mac
 - Laravel: 5.6
 - Model Caching: 0.3.6

**Comment by mikebronner** [comment]
PHP 5.6 is not supported.

**Comment by mahmod2000** [comment]
@mikebronner  I mentioned above PHP = 7.2 !  not  5.6
Laravel is 5.6
