### ISSUE TITLE
Installation request for genealabs/laravel-model-caching 

### ISSUE THREAD

**Issue by mahmod2000** [GeneaLabs/laravel-model-caching#206]
Hi
I just posted about this issue and you said it doesn't support PHP 5.6, but I said my PHP version is 7.2  and laravel version was 5.6.
Now I updated the laravel version to 5.7, but it still show the below error:

 `Problem 1
    - Installation request for genealabs/laravel-model-caching ^0.3.6 -> satisfiable by genealabs/laravel-model-caching[0.3.6].
    - genealabs/laravel-model-caching 0.3.6 requires fico7489/laravel-pivot dev-new@dev -> satisfiable by fico7489/laravel-pivot[dev-new] but these conflict with your requirements or minimum-stability.
`

**Environment**
 - PHP: 7.2
 - OS: Mac
 - Laravel: 5.7
 - Model Caching: 0.3.6

**Additional context**
I don't know what happens there, but it doesn't install on my local environment.

please give me a trick.

**Comment by jishadp** [comment]
@mahmod2000 Have you got the solutions ? Same issue for me as well. 

**Environment**

PHP: 7.2
OS: Ubuntu
Laravel: 5.6

**Comment by mikebronner** [comment]
@mahmod2000 sorry about the misunderstanding and delay on this issue. I think I know where the problem lies, and will try to get a fix out today or tomorrow. (It's most likely the dependency `Laravel-pivot` needs to be updated to a release version.)

**Comment by mikebronner** [comment]
@mahmod2000 @jishadp I released version 0.3.7 with an update to the dependency, which should fix your issue. Let me know how it goes. :)

**Comment by sgssxf** [comment]
Using version ^0.4.7 for genealabs/laravel-model-caching
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for genealabs/laravel-model-caching ^0.4.7 -> satisfiable by genealabs/laravel-model-caching[0.4.7].
    - genealabs/laravel-model-caching 0.4.7 requires mikebronner/laravel-pivot dev-master@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by mikebronner** [comment]
@sgssxf please see #219
