### ISSUE TITLE
checking cooldown

### ISSUE THREAD

**Issue by yassir3wad** [GeneaLabs/laravel-model-caching#207]
why the package checks cooldown:saved-at, cooldown:invalidated-at, and cooldown:seconds every time query requested where I am not using this feature in my model cache

![image](https://user-images.githubusercontent.com/31948375/52259942-04a99300-292d-11e9-80e5-83739aedef08.png)

**Comment by mikebronner** [comment]
@yassir3wad Thanks for highlighting this  possible issue. Can you provide the eloquent query you are running? That will help me look into it. Thanks!

**Comment by yassir3wad** [comment]
@mikebronner the query is simple `Country::get()`, the previous image was captured from laravel telescope

**Comment by umasslmz** [comment]
Same issue after installing on Laravel 5.8 and using latest Telescope. Extended model with BaseModel as instructed.

**Comment by mycarrysun** [comment]
@mikebronner you just fixed this with 0.4.10 and forward

**Comment by mikebronner** [comment]
@mycarrysun Love it when that happens! :) Closing for now. Please reopen if this recurs.

**Comment by joe820912boy** [comment]
Hi,

today I face the same problem with laravel 8, 

I try to log the return of "getCacheCooldownDetails"  and the return array is all null

The query is simple that just use Model::take(100)->get()

And here is the log:
```
[2022-12-20 09:15:07] local.INFO: getCacheCooldownDetails  
[2022-12-20 09:15:07] local.INFO:   
[2022-12-20 09:15:07] local.INFO:   
[2022-12-20 09:15:07] local.INFO:   
```

Here is my edit of getCacheCooldownDetails func.
```
    protected function getCacheCooldownDetails(
        Model $instance,
        string $cachePrefix,
        string $modelClassName
    ) : array {
        Log::info('getCacheCooldownDetails');
        Log::info($instance->cache()->get("{$cachePrefix}:{$modelClassName}-cooldown:seconds"));
        Log::info($instance->cache()->get("{$cachePrefix}:{$modelClassName}-cooldown:invalidated-at"));
        Log::info($instance->cache()->get("{$cachePrefix}:{$modelClassName}-cooldown:saved-at"));
        return [
            $instance
                ->cache()
                ->get("{$cachePrefix}:{$modelClassName}-cooldown:seconds"),
            $instance
                ->cache()
                ->get("{$cachePrefix}:{$modelClassName}-cooldown:invalidated-at"),
            $instance
                ->cache()
                ->get("{$cachePrefix}:{$modelClassName}-cooldown:saved-at"),
        ];
    }
```

**Comment by mikebronner** [comment]
@joe820912boy did you set the model to use cachecooldown? I believe cooldown will only work if explicitly set on the model.

**Comment by joe820912boy** [comment]
@mikebronner yes, I have set the cachecooldownseconds, 

```
    use Cachable;
    // protected $cachePrefix = "thoth8";
    protected $cacheCooldownSeconds = 300;

```

and in following function, I can see the cooldownseconds with "300" in my log

```
    public function getModelCacheCooldown(Model $instance) : array
    {
        if (! $instance->cacheCooldownSeconds) {
            return [null, null, null];
        }
        Log::info($instance->cacheCooldownSeconds);
        $cachePrefix = $this->getCachePrefix();
        $modelClassName = get_class($instance);
        [$cacheCooldown, $invalidatedAt, $savedAt] = $this
            ->getCacheCooldownDetails($instance, $cachePrefix, $modelClassName);

        if (! $cacheCooldown || $cacheCooldown === 0) {
            return [null, null, null];
        }

        return [$cacheCooldown, $invalidatedAt, $savedAt];
    }
```
