### ISSUE TITLE
Binary UUID data changes

### ISSUE THREAD

**Issue by drsdre** [GeneaLabs/laravel-model-caching#208]
I'm using ordered binary MySQL storage for UUID's. As soon as I'm switching on 'use cachable;' on my models, the UUID's suddenly change between the first and subsequent queries causing mismatches.

(Confirmed) original UUID 8cecda47-f2f6-46e3-8e92-9b100efc7273

Change to UUID 8cecc9dd-aaf9-4031-a239-56ab512dc6c9 when cachable is enabled on the models

**Environment**
 - PHP:  7.2.13
 - OS: MacOS with HomeBrew
 - MySQL: 8.0.13
 - Redis: 5.0.3
 - Laravel: 5.7.20
 - Model Caching: 0.3.6
 - dyrynda/laravel-model-uuid: 4.1.0
 - dyrynda/laravel-efficient-uuid: 2.2.0

**Comment by mikebronner** [comment]
Please provide more detail. We need at least the the eloquent query you are using, and complete stack traces for any errors. I don't have an answer for you based on the information provided so far, unfortunately.

**Comment by drsdre** [comment]
I have a strong suspicion the source of the problem is caused by not clearing the cache after a database reset and reseed. I'll do some more testing in the coming week.

**Comment by mikebronner** [comment]
@drsdre Yes, I have confused myself in debugging due to out-of-sync caches before as well! :) It would make sense with what you are experiencing. Let me know how it goes. I will close this for now, but if you find out more, please re-open it. :) Good luck!
