### ISSUE TITLE
Performance issue with `checkCooldownAndRemoveIfExpired`

### ISSUE THREAD

**Issue by yemenifree** [GeneaLabs/laravel-model-caching#209]
**Describe the bug**

I was testing the performance of the website with a huge number of requests in sametime but I found very critical issue with performance because of `checkCooldownAndRemoveIfExpired` function

its increase the response time from < 1s to > ~9s for each request when the server tried to serve > 400 requests per second, my test was done using different settings and using load balance for the web server and cache servers

after removing `checkCooldownAndRemoveIfExpired` from source code and use only model cache the server serves more than 2000 request per second without any issues or effect in response time

by the way, I don't use `cool-down` in my code

**Environment**

 - PHP: 7.2
 - OS: ubuntu 18.04.1
 - Laravel: 5.6
 - Model Caching: 0.3.6
 - 2 web servers
 - more than 500 request per second

## Perfomrnace with `checkCooldownAndRemoveIfExpired`

![image](https://user-images.githubusercontent.com/10876587/52403569-0a8fa780-2ad8-11e9-8556-b8a838176d86.png)

![image](https://user-images.githubusercontent.com/10876587/52404449-15e3d280-2ada-11e9-84c9-575b2e94689f.png)

## Perfomance without `checkCooldownAndRemoveIfExpired`

![image](https://user-images.githubusercontent.com/10876587/52403644-3dd23680-2ad8-11e9-98c1-de3bf51a4050.png)

**Comment by mikebronner** [comment]
Thanks for submitting this in detail! I will take a further look into this, hopefully this weekend. :)

**Comment by mycarrysun** [comment]
I can confirm - I found the same thing by analyzing the cache misses and that it is looking for the cooldown data even if it isn't there.

Are we able to add this to the config file somehow? 

I may write up a PR if I have some time.

**Comment by mikebronner** [comment]
Yes, a PR would help out tremendously. I haven't had a chance to analyze this issue yet. :(

**Comment by mycarrysun** [comment]
@mikebronner Just added - let me know what you think. The tests are failing somewhere before my tests run so not sure what's going wrong there.

Says: 
```
1) GeneaLabs\LaravelModelCaching\Tests\Integration\CachedBuilder\WhereJsonContainsTest::testWithInUsingCollectionQuery
Illuminate\Database\QueryException: SQLSTATE[08006] [7] timeout expired (SQL: select tablename from pg_catalog.pg_tables where schemaname = 'public')
```

**Comment by mikebronner** [comment]
Hi @yemenifree and @mycarrysun, would you guys mind testing release 0.4.10 to see if that fixes it? Please see the updated readme for enabling cache cool-down if you wish to use it. If not, you shouldn't have to make any changes. Please keep me updated as to how your performance testing goes. Thanks for all your help!

**Comment by mikebronner** [comment]
@mycarrysun I have updated the cachecooldown property on models to reflect seconds instead of a boolean, as we discussed yesterday.

**Comment by mycarrysun** [comment]
Awesome! What version is this in?

**Comment by mikebronner** [comment]
https://github.com/GeneaLabs/laravel-model-caching/commit/eeb78e0a2b0dc1ffdfe2d2669c5d3bc3d2274c6b

**Comment by mikebronner** [comment]
Closing this issue for now. Please let me know if there is still a performance impact! Thanks for your guys's help on this!

**Comment by mycarrysun** [comment]
Sorry for the late reply - just upgraded to 0.4.11 and is working as expected!

**Comment by mikebronner** [comment]
@mycarrysun Awesome! Thanks for following up. :)
