### ISSUE TITLE
Add Laravel 5.8 Compatibility

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#215]

**Comment by dmason30** [comment]
@mikebronner Since this contained breaking changes, namely the backwards compatibility shouldn't this have been a major release (1.0.0) not minor (0.4.0)?

**Comment by mikebronner** [comment]
@dmason30, no ... 0.x releases are breaking changes during the beta phase. 1.0.0 release would be the initial go-live. It is still in beta.
