### ISSUE TITLE
Laravel 5.8 constraint doesn't allow composer to pull >5.8.0

### ISSUE THREAD

**Issue by Phr33d0m** [GeneaLabs/laravel-model-caching#216]
Hi, as the title says. I was wondering why my ```composer update``` didn't pull the already available 5.8.2 release thus I ran:

```
$ composer prohibits laravel/framework:5.8.2
genealabs/laravel-model-caching  0.4.1  requires  illuminate/support (5.8)
```

Could you relax the requirement a bit? Something like 5.8.* should be correct.

Thanks.

**Comment by mikebronner** [comment]
@Phr33d0m haha, for sure!! sorry about that ... I was using the range specification before, where the patch version didn't matter. Fix coming up in a sec.

**Comment by Phr33d0m** [comment]
@mikebronner Thanks! 

Btw, I know this is a different issue but as I have your attention in here could you fix this as well for the next version bump?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - genealabs/laravel-model-caching 0.4.5 requires fico7489/laravel-pivot dev-patch-1@dev -> no matching package found.
```

I'm not a composer guru so I have no idea why it's not picking up the custom repository...

**Comment by mikebronner** [comment]
hmmmm, It **should** be pulling from my fork on GitHub ... I'll look into it some more.

**Comment by mikebronner** [comment]
I'm not able to replicate the problem, it downloads the patch for me everytime I try, even after clearing composer cache. Would you mind pasting your composer.json here for me to take a look at?

**Comment by Phr33d0m** [comment]
For me the error is reproducible every time. Just do ```laravel new testrepo && composer require genealabs/laravel-model-caching``` and it should fail.

**Comment by mikebronner** [comment]
@Phr33d0m This should now work in version 0.4.7.
