### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#217]
Continuation of issue #216 

Need to figure out how to get composer to resolve fork when installing.

**Comment by mikebronner** [comment]
@Phr33d0m I will continue working on this tomorrow. Sorry this isn't working at the moment. I've tried all sorts of advice from stackexchange.

Anyone know how to pull in a fork in a composer dependency's dependency?

**Comment by shanjo** [comment]
Hello, im guessing this is with the dependencies "fico7489/laravel-pivot"
As far as i can see its trying to retrieve the dev-xx etc. version which apparently doesn't exists anymore.

But what is the difference between their live version, wouldn't it be able to run with that or do it have to be the development version?

I dont know alot about the structure of your extension :) Just speaking on the top of my mind :)

**Comment by mikebronner** [comment]
@shanjo The problem is that composer won't install custom repositories defined in packages, only at the root level. I'm trying to figure out how to get around this until the `laravel-pivot`package is updated with this PR: https://github.com/fico7489/laravel-pivot/pull/57, so that people can install this package. :-|

**Comment by mikebronner** [comment]
This should now work in version 0.4.7.
