### ISSUE TITLE
Model::first() being treated as Model::all()?

### ISSUE THREAD

**Issue by iredmedia** [GeneaLabs/laravel-model-caching#218]
**Describe the bug**
On one specific model, when I add the trait, Model::first() gives me a full collection - as if Model::all() was called. Other models work fine. This occurs in tinker.

**Eloquent Query**
```php
$model->first()
```

**Stack Trace**
No errors thrown

**Environment**
 - PHP: 7.1.0
 - OS: OSX
 - Laravel: 5.5.14
 - Model Caching: laravel-5.5

**Additional context**
I'm using GeneaLabs/laravel-model-caching:dev-laravel-5.5, as no other composer install would work.

**Comment by mikebronner** [comment]
@iredmedia Thanks for posting this. If it's a bug in the package, it will only be fixed for Laravel 5.8, as I can no longer maintain backwards-compatibility to any released prior.

**Comment by mikebronner** [comment]
@iredmedia I am unable to replicate this issue. Please test with the latest release in Laravel 5.8 and re-open if it still occurs. Thanks :)
