### ISSUE TITLE
composer require genealabs/laravel-model-caching ^0.4.7

### ISSUE THREAD

**Issue by sgssxf** [GeneaLabs/laravel-model-caching#219]
**Describe the bug**
Using version ^0.4.7 for genealabs/laravel-model-caching
```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for genealabs/laravel-model-caching ^0.4.7 -> satisfiable by genealabs/laravel-model-caching[0.4.7].
    - genealabs/laravel-model-caching 0.4.7 requires mikebronner/laravel-pivot dev-master@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Environment**
 - PHP: 7.1.23
 - OS: mac os 10.13.6
 - Laravel: 5.8.*
 - Model Caching: ^0.4.7

**Comment by danishhashmi88** [comment]
Same

- PHP 7.1.3
- OS : Windows 10 
- Laravel: 5.6.4
- Model Caching: ^0.4.7

**Comment by mikebronner** [comment]
@sgssxf @danishhashmi88 Thanks for reporting this. I thought that was resolved when I was able to install it without issue. Grrrr.... I will try to resolve this early next week.

**Comment by mikebronner** [comment]
As a work-around, could you add the following to your project's composer.json file, until this issue is resolved?

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/mikebronner/laravel-pivot"
        }
    ],
```

Please let me know if the package resolves for you after that.

**Comment by danishhashmi88** [comment]
> As a temporary work-around, could you add the following to your project's composer.json file, until this issue is resolved?
> 
> ```
>     "repositories": [
>         {
>             "type": "vcs",
>             "url": "https://github.com/mikebronner/laravel-pivot"
>         }
>     ],
> ```
> Please let me know if the package resolves for you after that.

Same error.

![image](https://user-images.githubusercontent.com/5086707/53682259-b9ab5180-3d19-11e9-9290-737572601868.png)

**Comment by mikebronner** [comment]
I am unable to replicate this issue. Please to the following on your project:

Update your `composer.json` to include the following:
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/mikebronner/laravel-pivot"
        }
    ],
    "require": {
...
        "genealabs/laravel-model-caching": "0.4.7"
    },
```

Run the following commands:
```sh
composer clear-cache
rm -rf vendor
composer update
```

Each time I try this, it installs the dependencies.

**Comment by Smolevich** [comment]
Why don't you  publish `https://github.com/mikebronner/laravel-pivot` in package repository https://packagist.org?

**Comment by mikebronner** [comment]
@Smolevich That is my last resort step, I was hoping to avoid that, but it looks like there is no other way. Will do that shortly.

**Comment by mikebronner** [comment]
Please try version 0.4.8 and let me know how that goes.

**Comment by alirezamaleky** [comment]
Thanks for fixing this problem, I installed the version 0.4.8 without problems, there is no need to change the composer.json file.

**Comment by remzikocak** [comment]
Version 0.4.8 is working fine for me. Thanks for fixing

**Comment by danishhashmi88** [comment]
Yup, 0.4.8 working fine.

**Comment by mikebronner** [comment]
Awesome, thanks, closing now. :) looks like the original package will receive an update soon.

**Comment by andreshg112** [comment]
I cannot install any of the three latest versions:

`composer require genealabs/laravel-model-caching`
![imagen](https://user-images.githubusercontent.com/15859884/54058309-7e9a9980-41c3-11e9-8514-9bd30c806441.png)

`composer require genealabs/laravel-model-caching:0.4.8`
![imagen](https://user-images.githubusercontent.com/15859884/54058335-91ad6980-41c3-11e9-95cc-f14ecb97709f.png)

`composer require genealabs/laravel-model-caching:0.4.7`
![imagen](https://user-images.githubusercontent.com/15859884/54058372-a558d000-41c3-11e9-9652-f50c1d86df00.png)

I already had this on my `composer.json` file:
```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/mikebronner/laravel-pivot"
        }
    ]
```

**Comment by mikebronner** [comment]
@andreshg112 This requires Laravel 5.8.

**Comment by Polyhistor** [comment]
On Laravel 7 issue still exists...

**Comment by mikebronner** [comment]
Hi @Polyhistor, unfortunately support is limited to the latest Laravel release only.

**Comment by Polyhistor** [comment]
@mikebronner that's a pitty! thanks for the swift reply
