### ISSUE TITLE
Keys are being deleted after executing phpunit

### ISSUE THREAD

**Issue by andreshg112** [GeneaLabs/laravel-model-caching#221]
**Describe the bug**
After executing `vendor/bin/phpunit`, Redis' keys are being deleted. In the image below, you can see the highlighted statement (after phpunit was executed).
![imagen](https://user-images.githubusercontent.com/15859884/54161145-47c0bf80-441f-11e9-8e4b-7fd37fd139ac.png)

**Environment**
 - PHP: 7.2.13
 - OS: 
 - Laravel: 5.6.39
 - Model Caching: 0.3.7

**Additional context**
 - Docker image: php:7.2-fpm
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by mikebronner** [comment]
Hi @andreshg112, that is by design. The unit tests check for various states, lingering caching, etc. etc., and need to flush the cache between every test. Can you describe why this is causing a problem for you?

**Comment by andreshg112** [comment]
It's not causing a problem right now. I just wanted to know why It's happening. In fact, It's about fear. We do have dev dependencies installed on our production environment for debugging purposes. Despite I'm the only one managing the Laravel backend right now, I would like to prevent deleting cache after executing PHPUnit or warn about it.
