### ISSUE TITLE
Transaction style disabling model cache

### ISSUE THREAD

**Issue by mycarrysun** [GeneaLabs/laravel-model-caching#234]
**Is your feature request related to a problem? Please describe.**
I am always having to disable the model cache on certain queries with lazy loaded relationships. I have created a helper for myself and figured others would find it useful for running an entire block of code with the model cache disabled and then turned on after the function is ran.

Here is my definition:
```php
public function disableModelCache(callable $closure)
{
    //get the current value
    $pre_config = config('laravel-model-caching.disabled');

    //disable model cache
    config(['laravel-model-caching.disabled' => true]);

    //run the function
    $closure();

    //reset the config
    config(['laravel-model-caching.disabled' => $pre_config]);
}
```

In my project I have a `Helpers` facade that the function lives in and can be used like this.

```php
Helpers::disableModelCache(function(){
    // do things here with model cache disabled
});

//model cache is re-enabled here
```

**Comment by mikebronner** [comment]
Hi @mycarrysun, thanks for suggesting this. Does the `->disableCache()` in the eloquent chain not work in your use-cases? If you could explain why that doesn't work, that will help me understand the specific use-case for this way better. Thanks! :)

**Comment by mycarrysun** [comment]
It does work now yes. Thanks :)

This is more of a convenience thing. I am using it in 2 places where I have multiple lazy load calls that I do not want loaded from the model cache and it is being called by a relation magic getter, which is not an eloquent query (eg `$this->cartable->load(['relation1', 'relation2']);` - where cartable is a relation of `$this` and I don't want `relation1` or `relation2` loaded from model cache). Now, in this situation I believe I can just call `$this->cartable()->disableCaching()->get()->load(['relation1', 'relation2']);` but that is a much big refactor than wrapping a block of code in a callable.

It is also convenient if you are calling functions that are also calling eloquent queries inside other classes/methods that you don't want to add another param just to flag if you want model cache enabled/disabled.

Hope this makes sense.

**Comment by mikebronner** [comment]
Hi @mycarrysun, this is now in release 0.4.13. :) Thanks for the suggestion. Please see the readme for implementation details.

**Comment by mycarrysun** [comment]
Nice man! Thanks for adding so quickly!

**Comment by mycarrysun** [comment]
Looks good - just peeped the readme
