### ISSUE TITLE
Soft delete

### ISSUE THREAD

**Issue by tmishutin** [GeneaLabs/laravel-model-caching#237]
**Describe the bug**
It seems like there is an issue with soft delete. If model using soft delete and result of NOT deleted query is cached, library will ignore global scoping of soft delete scope for the model which will result in wrong return.

**Eloquent Query**
The following will not find a deleted item
```php
Book::withTrashed()->find($id)
```

However the following WILL find the deleted item
```php
Book::whereNotNull('deleted_at')->find($id)
```

**Stack Trace**
-

**Environment**
 - PHP:7.2
 - OS: Debian stretch
 - Laravel: 5.8
 - Model Caching: 0.4.11

**Comment by jcsoriano** [comment]
FWIW, I was also able to replicate this error.

`Book::withTrashed()->find($id)` doesn't work, but `Book::onlyTrashed()->find($id)` works fine

`Book::withTrashed()->get()` also doesn't include the soft-deleted models

Environment:
* PHP: 7.2
* OS: Mac OS
* Laravel: 5.8
* Model Caching: 0.4.13

**Comment by mikebronner** [comment]
Will investigate soon, thanks for reporting this :)

**Comment by mikebronner** [comment]
Am working on this, have confirmed that this functionality is missing. Any PR to help with this is welcomed :)

**Comment by mikebronner** [comment]
Good news, while working on fixing how global scopes were parsed, I think I may have found a way to implement this as well. Stay tuned!

**Comment by mikebronner** [comment]
@tmishutin @jcsoriano Could you guys test release 0.5.5 and let me know how it works for you? This should now be fixed! :) 🎉
