### ISSUE TITLE
Cached queries with different select fields statement 

### ISSUE THREAD

**Issue by mrahmadt** [GeneaLabs/laravel-model-caching#238]
**Describe the bug**
Query database with deferent fields (and same "where" statement) will return the first cached result without respecting the requested/selected fields 

**Eloquent Query**
```php
public function getChildren(Request $request){ //---> return all fields
return Child::where(['user_id'=>$request->auth->id])->get();
}

public function getNames(Request $request){ //---> Should return only "id" & "name"
return Child::where(['user_id'=>$request->auth->id])->select('id','name')->get();
}

```
**Environment**
 - PHP: 7.3
 - OS: Ubuntu 18.04.1
 - laravel/lumen-framework: v5.7.8
 - Model Caching: 0.3.7

**Comment by jcsoriano** [comment]
The interesting thing is specifying the columns within the `->get('...')` method works, but specifying it through `->select('...')` doesn't. So as a temporary workaround, maybe you should put your columns in `->get()` instead of `->select()`, like below:

```
Child::where(['user_id' => $request->auth->id])->get(['id', 'name']);
```

*Environment*
* PHP: 7.2
* OS: Mac OS
* Laravel: 5.8.11
* Model Caching: 0.4.13

**Comment by mrahmadt** [comment]
Excellent.

Thanks, this is working fine when I put columns in get().

**Comment by mikebronner** [comment]
Keeping this issue open to investigate the `select()` issue.

**Comment by mikebronner** [comment]
This is indeed a bug, will need to ponder on this a while to see how to implement this.

**Comment by dmason30** [comment]
@mikebronner I think this one can be closed the test seems to pass?

**Comment by mikebronner** [comment]
@dmason30 Thanks for checking on this! :)

**Comment by peter-brennan** [comment]
Is this still an issue?
