### ISSUE TITLE
Polymorphic relationships error out when caching is enabled.

### ISSUE THREAD

**Issue by smapod** [GeneaLabs/laravel-model-caching#239]
I updated LMC from 0.3.6 to 0.4.14, and morph relationships broke.

**Explanation:**

1. I call php artisan cache:clear to clear cache.
2. I get products and their prices using eager-load for the first time, everything is fine.

![Step 2](https://i.imgur.com/zj4nMcF.png)

3. I get other products and their prices, the query to the database is cached and not displayed in the console, of course cache doesn't have this data - relationships is not returned.

![Step 3](https://i.imgur.com/rST0HGJ.png)

Expecting missed query:

![Query](https://i.imgur.com/hDsZMAp.png)

**Product model:**

![Product](https://i.imgur.com/evDhzd8.png)

**Price model:**

![Price](https://i.imgur.com/2fV2eqH.png)

In 0.3.6 all worked fine.

**Comment by mikebronner** [comment]
@smapod Thanks for reporting this. I will look into this over the next few days.

**Comment by mikebronner** [comment]
@smapod Can you provide your eloquent query that uses the morph? This will help me create a test case. Thanks!

**Comment by smapod** [comment]
It's not original, but the same (clear custom scopes).

```
$products = Product::with(['color', 'glass', 'price', 'icons'])
            ->where('category_id', $category->id)
            ->where('active', 1)
            ->orderBy('position')
            ->paginate(60);
```

**Comment by smapod** [comment]
Corrected the answer.

**Comment by mikebronner** [comment]
@smapod awesome, thanks for the additional details. I will try to look into this over the next few days.

**Comment by mikebronner** [comment]
Likely related to #225

**Comment by mikebronner** [comment]
@smapod can you test this again with version `0.4.15`? I have a feeling the `whereIn` fix might also have fixed this. Please let me know how it works. Thanks!

**Comment by mikebronner** [comment]
@smapod Actually, if you could test with 0.4.17, just released, which addresses an issue with where clause generation for the cache key.

**Comment by smapod** [comment]
Problem still exists.

I created repo https://github.com/smapod/lmc-bug, hope it will.

**Comment by mikebronner** [comment]
@smapod Thanks for the repo. I will test and see if I can reproduce.

**Comment by mikebronner** [comment]
@smapod  This is going to take a while to figure out, if it's at all possible. In the mean time, I would recommend removing any models that implement polymorphic relationships from being cachable. You should still be able to leave the other models cachable.

If anyone has any ideas on how to fix this, I certainly would welcome a PR. Thanks :)

**Comment by mikebronner** [comment]
@smapod  Update: actually got it working correctly in your example repo, thanks so much for that. Now testing the fix and creating a test case for it. Hope to have this fix out this evening or tomorrow.

**Comment by mikebronner** [comment]
@smapod Please test with release 0.4.18 or above and let me know how it works. Thanks for your patience and support on getting this resolved. Your repo did the trick! :)

**Comment by mikebronner** [comment]
@smapod Awesome, that's great to hear! :)
