### ISSUE TITLE
BUG: where('category', 0) and where('category', 1)  use same cache key

### ISSUE THREAD

**Issue by zhenyangze** [GeneaLabs/laravel-model-caching#240]
**Describe the bug**
when the select field data is empty, the cache key would wrong.

**Eloquent Query**
Please provide the complete eloquent query that caused the bug, for example:
```php
$model->where('level', 1)->where('category', 0);
and 
$model->where('level', 1)->where('category', 1);
```

**Stack Trace**
no error

**Environment**
 - PHP: [e.g. 7.1.0]
 - OS: [mac]
 - Laravel: [5.6.15]
 - Model Caching: [^0.3.0]

**Additional context**
in file: vendor/genealabs/laravel-model-caching/src/CacheKey.php
```php
    protected function getValuesFromBindings(array $where, string $values) : string
    {
        if (! $values && ($this->query->bindings["where"][$this->currentBinding] ?? false)) {
            $values = $this->query->bindings["where"][$this->currentBinding];
            $this->currentBinding++;

            if ($where["type"] === "between") {
                $values .= "_" . $this->query->bindings["where"][$this->currentBinding];
                $this->currentBinding++;
            }
        }

        return $values ?: "";
    }
```

if the $values is equal 0;the return value will use another bindings value

**Comment by mikebronner** [comment]
@zhenyangze Thanks for reporting this, will look into it soon!

**Comment by mikebronner** [comment]
Likely related to #225

**Comment by mikebronner** [comment]
@zhenyangze Are you running this on Laravel 5.8? You are likely not running the latest version of this plugin. What is the installed version of the plugin (check composer.lock)?

**Comment by mikebronner** [comment]
@zhenyangze Please test with version 0.4.17 or greater, I addressed an issue with where clauses not applying correctly to the cache key.

**Comment by zhenyangze** [comment]
thanks, i use old version, and the latest version is ok

**Comment by mikebronner** [comment]
Thanks, @zhenyangze , unfortunately old versions prior to Laravel 5.8 are not supported, so use them at your own risk. Glad to hear the latest update seems to work, though. :)
