### ISSUE TITLE
Cache Expire (no forever cache)

### ISSUE THREAD

**Issue by ktanakaj** [GeneaLabs/laravel-model-caching#243]
**Is your feature request related to a problem? Please describe.**
I use redis memory cache store. I don't have large memory.
But I guess laravel-model-caching reserve memory for a long term because it use `Cache::rememberForever` only.

**Describe the solution you'd like**
I want to set cache expire to remove inactive records.

The expire may be configured like the following.
`config(['laravel-model-caching.cache-prefix' => 'test-prefix']);`
`protected $cacheCooldownSeconds = 300;`

**Describe alternatives you've considered**
I overrode `CachedBuilder` and replaced `rememberForever` to `remember` like [this](https://github.com/ktanakaj/social-game-api-example/commit/633fa2996cd6b4fd2243180be6c342140f925183#diff-493e7733e8339db65a5de3a7df30d258).

**Comment by mikebronner** [comment]
@ktanakaj This shouldn't be necessary, as Redis and MemCached will remove old cache entries automatically when it needs more space.

**Comment by mikebronner** [comment]
Closing issue for now, please re-open if you don't see redis behaving as expected.

**Comment by ktanakaj** [comment]
Thanks. But I can't change max memory policy because my redis has not cache only.
There are session data and user temporary data too...
I will use my custom CachedBuilder.

**Comment by mikebronner** [comment]
@ktanakaj That shouldn't really matter. Redis will still purge stale records if it needs more cache space. With proper configuration Redis can be set up to utilize virtual memory (storing stale records off to disk, instead of purging) in conjunction with memory limits.
