### ISSUE TITLE
I am having a similar problem with a library that generates a query using the where type 'InRaw'. I took a screenshot of the $wheres variable of the $query object in CacheKey:

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#245]
I am having a similar problem with a library that generates a query using the where type 'InRaw'. I took a screenshot of the $wheres variable of the $query object in CacheKey:
<img width="336" alt="Screen Shot 2019-05-10 at 22 34 24" src="https://user-images.githubusercontent.com/180665/57555177-dc8a5f80-7373-11e9-8f5f-82455f25de51.png">

In this example the cache key should use 1 as value of the InRaw where clause, however the function `getValuesClause()` replaces 1 with the last value from the `$this->query->bindings['where']` array in `getValuesFromBindings()`. In this array 1 is not included. See:
<img width="225" alt="Screen Shot 2019-05-10 at 22 34 45" src="https://user-images.githubusercontent.com/180665/57555370-65a19680-7374-11e9-94d1-dfb772f3a067.png">

It appears the bindings array is not correctly formed. This generates double cache keys, which break the model caching library for raw where clauses.

As far as I could debug, either the bindings array should also include the raw values or you should rely on the results of `getValuesFromWhere()` in `getValuesClause()`, which correctly returns 1. I have changed the code of getValuesClause to this, which works:

```
protected function getValuesClause(array $where = null) : string
    {
        if (in_array($where["type"], ["NotNull", "Null"])) {
            return "";
        }

        $values = $this->getValuesFromWhere($where);
        if($where['type'] != 'InRaw') {
            $values = $this->getValuesFromBindings($where, $values);
        }

        return "_" . $values;
    }
```

This should probably be further extended for other raw types. I hope this helps!

_Originally posted by @sten in https://github.com/GeneaLabs/laravel-model-caching/issues/244#issuecomment-491424429_

**Comment by mikebronner** [comment]
@sten please provide the eloquent query, as well as what version of Laravel, and that of the package you have installed.

**Comment by mikebronner** [comment]
@sten Please try version 0.4.17 that addresses an issue with how `where` clauses are parsed for cache key generation. Let me know how that works for you. Thanks!

**Comment by sten** [comment]
@mikebronner Sorry, I just now saw your request for a query. I checked the new version of the library and it works! Thanks a lot for the quick fix!!!

**Comment by mikebronner** [comment]
@sten That's awesome! Thanks for reporting back :)
