### ISSUE TITLE
0.4.21

### ISSUE THREAD

**Issue by tmishutin** [GeneaLabs/laravel-model-caching#248]
**Describe the bug**
After updating till 21, I get the following error.

**Eloquent Query**
-

**Stack Trace**
{
    "message": "Trait 'GeneaLabs\\LaravelModelCaching\\Traits\\Buildable' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/home/vagrant/code/vendor/genealabs/laravel-model-caching/src/CachedBuilder.php",
    "line": 10,
    "trace": [
        {

**Environment**
- PHP:7.2
- OS: Debian stretch
- Laravel: 5.8
- Model Caching: 0.4.11

**Comment by mikebronner** [comment]
Checking ...

**Comment by mikebronner** [comment]
Ugh! Thanks for reporting this ... found the issue, I think. It didn't manifest in testing because of the testing environment. Fixing that now.

**Comment by mikebronner** [comment]
@tmishutin Go ahead and give 0.4.22 a try. Let me know how that works :) Thanks again!
