### ISSUE TITLE
Passing DateTime object to where clause

### ISSUE THREAD

**Issue by kangoo13** [GeneaLabs/laravel-model-caching#253]
**Describe the bug**
Giving an DateTime to the where clause statement throws an error.

**Eloquent Query**
Please provide the complete eloquent query that caused the bug, for example:
```php
$dateAgo       = (new \DateTime('@' . time()))->sub(new \DateInterval(static::EXPIRACY_MESSAGE_CACHE_DELAY));
$eloquentModel = Eloquent::where('cache_set_at', '<=', $dateAgo)
                                     ->get();
```

**Stack Trace**
[2019-05-21 14:00:19] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Return value of GeneaLabs\LaravelModelCaching\CacheKey::getValuesFromWhere() must be of the type string, object returned in /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/CacheKey.php:169
Stack trace:
#0 /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/CacheKey.php(145): GeneaLabs\LaravelModelCaching\CacheKey->getValuesFromWhere(Array)
#1 /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/CacheKey.php(309): GeneaLabs\LaravelModelCaching\CacheKey->getValuesClause(Array)
#2 /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/CacheKey.php(196): GeneaLabs\LaravelModelCaching\CacheKey->getOtherClauses(Array)
#3 [internal function]: GeneaLabs\LaravelModelCaching\CacheKey->GeneaLabs\LaravelModelCaching\{closure}(NULL, Array)
#4 /home/deploy/projects/callbot/releases/281/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1501): array_reduce(Array, Object(Closure), NULL)
#5 /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/CacheKey.php(199): Illuminate\Support\Collection->reduce(Object(Closure))
#6 /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/CacheKey.php(40): GeneaLabs\LaravelModelCaching\CacheKey->getWhereClauses()
#7 /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(84): GeneaLabs\LaravelModelCaching\CacheKey->make(Array, NULL, '')
#8 /home/deploy/projects/callbot/releases/281/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(94): GeneaLabs\LaravelModelCaching\CachedBuilder->makeCacheKey(Array)
#9 /home/deploy/projects/callbot/releases/281/app/Services/Media/MediaService.php(81): GeneaLabs\LaravelModelCaching\CachedBuilder->get()

**Environment**
 - PHP: 7.2.17
 - OS: Ubuntu 16
 - Laravel: 5.8
 - Model Caching: 0.5.0

**Additional context**
Seems like the where statement doesn't like DateTime object! 

Thanks !

**Comment by mikebronner** [comment]
@kangoo13 Thank you for reporting this! I will get a test case set up and see if I can get a fix in ASAP.

**Comment by mikebronner** [comment]
@kangoo13 Can you give me the text value of your constant `static::EXPIRACY_MESSAGE_CACHE_DELAY`? That would help me get the test case set up.

**Comment by kangoo13** [comment]
@mikebronner 

```
    const EXPIRACY_MESSAGE_CACHE_DELAY            = 'P1M';
```

**Comment by mikebronner** [comment]
@kangoo13 Thanks! Go ahead and give release 0.5.1 a try and let me know how that works for you.

**Comment by kangoo13** [comment]
@mikebronner Thank you for your quick intervention ! Are you sure you did push the code ? The release 0.5.1 seems to have an empty commit

see : https://github.com/GeneaLabs/laravel-model-caching/releases/tag/0.5.1

**Comment by mikebronner** [comment]
@kangoo13 Ooops!!!  You're right, I forgot to push the changes. Try 0.5.2. Sorry about that. :)

**Comment by kangoo13** [comment]
Seems to be working now, thank you ! :)

**Comment by mikebronner** [comment]
@kangoo13 awesome! Thanks for reporting back :)
