### ISSUE TITLE
Global Scopes Possibly Not Working Again?

### ISSUE THREAD

**Issue by kolirt** [GeneaLabs/laravel-model-caching#256]
**Describe the bug**
SQL queries cached, but always return first cached query. The SQL queries make a [package](https://github.com/kolirt/laravel-translations), namely a [generateQuery](https://github.com/kolirt/laravel-translations/blob/d72b89fb1afe00a4dad844b5073040ba0108e8e9/src/Traits/Translatable.php#L204) method

Help me, please. It's very **important problem.** I don't know what I need to do to worked it

**SQL Query**
First SQL query
```sql
select articles.*, (SELECT `string` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='name') as `name`, (SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='short_description') as `short_description`, (SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='text') as `text`, (SELECT `string` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='meta_title') as `meta_title`, (SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='meta_description') as `meta_description` from `articles` where `slug` = 'ivanchenko-bogdan-yosipovich' and `active` = 1 limit 1
```

Second SQL query
```sql
select articles.*, (SELECT `string` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='en' AND `key`='name') as `name`, (SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='en' AND `key`='short_description') as `short_description`, (SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='en' AND `key`='text') as `text`, (SELECT `string` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='en' AND `key`='meta_title') as `meta_title`, (SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='en' AND `key`='meta_description') as `meta_description` from `articles` where `slug` = 'ivanchenko-bogdan-yosipovich' and `active` = 1 limit 1
```
This queries are different by lang key in subquery

**Environment**
 - PHP: 7.2.17
 - OS: Ubuntu 18.04.1
 - Laravel: 5.8.18
 - Model Caching: 0.5.3

**Comment by mikebronner** [comment]
@kolirt Please submit the Eloquent queries used in your code. That will help me narrow down the problem. Thanks :)

**Comment by kolirt** [comment]
> @kolirt Please submit the Eloquent queries used in your code. That will help me narrow down the problem. Thanks :)

Problem in this sql subqueries
```sql
(SELECT `string` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='name') as `name`, 
(SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='short_description') as `short_description`, 
(SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='text') as `text`, 
(SELECT `string` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='meta_title') as `meta_title`, 
(SELECT `text` FROM `translations` WHERE `translation_id`=`articles`.`id` AND `translation_type`='articles' AND `lang`='uk' AND `key`='meta_description') as `meta_description`
```

<hr>

BlogController
```php
public function article(Request $request, Article $article)
{
    return view('pages.article', compact('article'));
}
```

Article (model)
```php
class Article extends Model
{

    use Translatable, Cachable, Activable;

    protected $fillable = [
        'name',
        'slug',
        'image',
        'short_description',
        'text',
        'meta_title',
        'meta_description',
        'active'
    ];

    protected $translatable = [
        'name',
        'short_description' => 'text',
        'text' => 'text',
        'meta_title',
        'meta_description' => 'text'
    ];


    public function getRouteKeyName()
    {
        return 'slug';
    }
}
```

Activable (trait)
```php
trait Activable
{

    public static function bootActivable()
    {
        static::addGlobalScope('active', function($builder){
            $builder->where('active', true);
        });
    }

}
```

Translatable (trait) ([you can see full code this trait](https://github.com/kolirt/laravel-translations/blob/master/src/Traits/Translatable.php))
```php
trait Translatable
{
    public static function bootTranslatable()
    {
        $class = new self;

        if (!empty($class->translatable) && config('translations.active', true)) {
            static::addGlobalScope('translatable', function(Builder $builder) use ($class){
                $builder->addSelect(\DB::raw($class->getTable() . ".*"));

                foreach ($class->translatable as $column => $type) {
                    $builder->addSelect($class->generateQuery($class, $column, $type));
                }
            });
        }
    }

    private function generateQuery($class, $column, $type)
    {
        if (!in_array($type, Translation::COLUMN_TYPE)) {
            $column = $type;
            $type = Translation::COLUMN_TYPE[0];
        }

        return \DB::raw("(SELECT `" . $type . "` FROM `translations` WHERE `translation_id`=`" . $class->getTable() . "`.`" . $class->getKeyName() . "` AND `translation_type`='" . $class->getTable() . "' AND `lang`='" . app()->getLocale() . "' AND `key`='" . $column . "') as `" . $column . "`");
    }
}
```

**Comment by mikebronner** [comment]
@kolirt Only eloquent queries will be cached. You are running a Query Builder query, which will not be cached, and could cause problems.

My recommendation would be to rewrite this functionality using eloquent. Since you are using `addSelect()` to add the Query Builder query to the Eloquent query, I believe the problem lies in that we currently cannot cache select clauses.

I will see if I can recreate this in a unit test, but for now I would recommend rewriting this to be completely eloquent.

**Comment by kolirt** [comment]
@mikebronner 

I can't understand how to rewrite. Please, can you prompt me?

**Comment by mikebronner** [comment]
@kolirt Actually, I take that back. I just added a test, and it caches the select query correctly. I am unable to replicate your problem.

Sorry, I can't provide support for rewriting app functionality, as I would need complete access to the app, and it could take hours or even days to rewrite something like this.

I can't say for sure why things aren't working as expected. If you could create an integration test that reproduces the issue, I can problem help more, and likely find a solution. For examples, see the last one here: https://github.com/GeneaLabs/laravel-model-caching/blob/master/tests/Integration/CachedBuilder/SelectTest.php

**Comment by kolirt** [comment]
@mikebronner 


I created example [project](https://github.com/kolirt/laravel-model-caching-test) on github and invited you to project

I wrote code that causes an error in [TestController](https://github.com/kolirt/laravel-model-caching-test/blob/master/app/Http/Controllers/TestController.php). Don't forget to start the migration

I will be grateful for help. Thanks

**Comment by mikebronner** [comment]
Sounds good, I will take a look later on.

**Comment by mikebronner** [comment]
@kolirt I tried taking a look at your test project. I was unable to fix the problem, but I know it lies in the `bootTranslatable()` method. It is not applying the addSelect to the correct object. I'm unable to recreate the issue in my own tests in this package. Why doesn't your taggable package utilize Eloquent for its tag lookups? I'm afraid I don't have more time to dig into this, sorry. If you can create a unit test within this package that reproduces the issue in a PR, I'll be more than happy to help.

**Comment by kolirt** [comment]
@mikebronner 

Seems to be a problem with addGlobalScope. You wrote about this problem here https://github.com/GeneaLabs/laravel-model-caching/issues/199#issuecomment-445429917. When will this problem be solved?

**Comment by mikebronner** [comment]
Hi @kolirt, this should already be resolved -- global scopes are working in the unit tests:
https://github.com/GeneaLabs/laravel-model-caching/blob/master/tests/Integration/CachedBuilder/ScopeTest.php

**Comment by kolirt** [comment]
@mikebronner 

Is it already in release? Local scope  works, but global scope don't works

**Comment by mikebronner** [comment]
@kolirt yes, it has been for a while. Global scopes work when applied to the models. I believe that in your case the problem is with how the `addSelect` is applied within the scope, not the scope itself.

**Comment by kolirt** [comment]
@mikebronner 

I checked. addSelect has nothing to do with the problem. The problem is in the GlobalScope

### Model
```php
<?php

namespace App;

use App\Scopes\Activable;
use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{

    use Cachable, Activable;

    protected $fillable = ['name', 'description', 'active'];

}
```

### Activable scope
```php
<?php

namespace App\Scopes;

trait Activable
{

    public static function bootActivable()
    {
        static::addGlobalScope('active', function($builder){
            $builder->where('active', 1);
        });
    }

}
```

### Controller
```php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TestController extends Controller
{

    public function index(Request $request)
    {
        dump('with globalScope');
        $tags = Tag::query()->get();
        foreach ($tags as $tag) {
            dump($tag->toArray());
        }

        dump('without globalScope');
        $tags = Tag::query()->withoutGlobalScope('active')->get();
        foreach ($tags as $tag) {
            dump($tag->toArray());
        }

        dump('without globalScope and cacheable');
        $tags = Tag::query()->disableCache()->withoutGlobalScope('active')->get();
        foreach ($tags as $tag) {
            dump($tag->toArray());
        }
    }

}
```

### Result
![image](https://user-images.githubusercontent.com/11573343/58434314-b8dd4e00-80c3-11e9-9e8c-74db4745f3ac.png)

**Comment by mikebronner** [comment]
@kolirt I'm going through the global scope tests and re-evaluating the process. I will report back in a bit.

**Comment by mikebronner** [comment]
@kolirt My apologies, and thank you for being persistent. I have confirmed that the GlobalScope functionality is not working as intended. I am working on a fix, hopefully I will have something ready over the next day or so.

**Comment by mikebronner** [comment]
@kolirt Can you give release 0.5.4 a try and let me know how it goes?

**Comment by kolirt** [comment]
@mikebronner 

It works. Thanks

**Comment by mikebronner** [comment]
Awesome, that's great to hear. Be sure to update again ... I released version 0.5.5 which adds support for the soft-delete-related macros.

**Comment by kolirt** [comment]
Hi there! Unfortunately, this problem is back again :(

**Comment by mikebronner** [comment]
@kolirt please prove all the details necessary to debug this: pacjage version, Laravel version, full stack trace of any error, etc.

**Comment by mikebronner** [comment]
@kolirt Would you mind testing this against release 0.8.4 or newer? Additional functionality has been added to deal with global scopes. Please let me know how it works for you.
