### ISSUE TITLE
Multiple Laravel/Lumen instances using single database

### ISSUE THREAD

**Issue by mrahmadt** [GeneaLabs/laravel-model-caching#259]
Hi

This is just a question, I'm building an application using multiple Laravel/Lumen instances (microservices), all of these instances will use a single database, what is the best option for me to make sure the caching will be invalidated across all instances if I update/create/delete something in the database?

Example:

Laravel A:  update products name to "ABC"

Lumen C: select product name will be "ABC"

For example can I setup a cache prefix in my .env file?

Thanks

**Comment by mikebronner** [comment]
Hi, as long as each instance is using the same of the following, they will invalidate automatically:
- same Redis server
- same database
- same prefix
- same connection name

Let me know if you have any trouble. Good luck! :)

**Comment by mrahmadt** [comment]
I'm using same server/database/connection but not sure about the prefix

Do you mean in cache.php I have to change this line in all instances to be the same?

'prefix' => env('CACHE_PREFIX', Str::slug(env('APP_NAME', 'lumen'), '_').'_cache'),

I was just afraid this will affect laravel/lumen internal caching.

**Comment by mikebronner** [comment]
No, this shouldn't affect internal caching in any way, as it uses Laravel's caching functionality. If you don't manually set the cache prefix anywhere it will be the same for all.
:)
