### ISSUE TITLE
consider changing MODEL_CACHE_DISABLED to MODEL_CACHE_ENABLED

### ISSUE THREAD

**Issue by vesper8** [GeneaLabs/laravel-model-caching#266]
this is a bit nitpicky but the thing is every other package that I've ever used that can be disabled via the config uses a SOMETHING_ENABLED format

Laravel Telescope, Laravel Debugbar, Laravel ResponseCache to name a few

Yours is the opposite and it's just not very intuitive IMHO and just now confused me as I meant to disable it while debugging a problem and didn't immediately realize I had to use the opposite boolean for your package

Possibly you could support the new key while still also supporting the old one. Or rename the key in a new major version.. Food for thought

**Comment by mikebronner** [comment]
Thanks @vesper8, yea, I had noticed the same thing. I will look into changing it for the next breaking release.

**Comment by mikebronner** [comment]
@vesper8 This is now in release 0.6.0. Let me know how it works for you.
