### ISSUE TITLE
pivot-events still needed?

### ISSUE THREAD

**Issue by Surt** [GeneaLabs/laravel-model-caching#268]
I was wondering if https://github.com/GeneaLabs/laravel-pivot-events is still needed on laravel 5.8?

> Intermediate Table / Pivot Model Events
In previous versions of Laravel, Eloquent model events were not dispatched when attaching, detaching, or syncing custom intermediate table / "pivot" models of a many-to-many relationship. When using custom intermediate table models in Laravel 5.8, the applicable model events will now be dispatched.

Before 5.8 I was using https://github.com/chelout/laravel-relationship-events for some of my models and now, updating to 5.8 I find that this conflicts with model-caching. I'm on the process of getting rid of https://github.com/chelout/laravel-relationship-events and wondering if you can do the same with https://github.com/GeneaLabs/laravel-pivot-events.

**Comment by mikebronner** [comment]
Hi @Surt, thanks for writing! We specifically created the laravel-model-events package to address pivot model events not being fired by Laravel natively. This package is still required in order to properly invalidate model caches when updated through relationships.

I will update the documentation to note that this package conflict exists.

**Comment by Surt** [comment]
Hi sorry for bother you again, Laravel 5.8 now fires events on pivot models (at least thats what says in the documentation I posted above). There is no need now for the laravel-relationship-events library. Am I wrong?

**Comment by mikebronner** [comment]
Hi @Surt, these were not being fired last I checked, but I will evaluate the issue again and report back. Thanks for re-raising your concern.

**Comment by mikebronner** [comment]
@Surt After looking at this more closely, this doesn't satisfy our requirements -- we need to know the model and the relationship it triggers at the same time, to be able to clear the cache for both models. Laravel is only firing events for one side of the equation, and we need both for this package to operate correctly. Until Laravel actually fires events for the pivots themselves, and not just for the models on either end, we will need the additional overhead of the laravel-pivot-events package.

I'll be happy to consider a PR if you have a solution that would allow us to get rid of that package. :) I'll close this for now, but feel free to re-open if you have additional info.
