### ISSUE TITLE
Call to undefined method App\Models\User\User::flushCache()

### ISSUE THREAD

**Issue by lukacavic** [GeneaLabs/laravel-model-caching#273]
Hi, I have this error when performing some operations. For example: I have a user model, I did not add Cachable trait to it. Also I have Announcement model, that model has Cachable trait.  I have link table link_announcement_users, and when I delete announcement, I also call: $announcement->users()->detach(); to remove entries from link table. And get this error

**Comment by mikebronner** [comment]
@lukacavic 
 Thanks for reporting this. I'll have a look in the next few days.

**Comment by lukacavic** [comment]
Hi, thanks for reply. Maybe suggestion.  Please check this image. I think this is bug. [https://imgur.com/bNyE4qw](url)

**Comment by mikebronner** [comment]
@lukacavic Nice catch!

**Comment by lukacavic** [comment]
Tnx, dont know to use GitHub to make a pull request. Please can you write a comment when you fix this? Thanks

**Comment by mikebronner** [comment]
Sure thing, probably later today or tomorrow. :)

**Comment by Surt** [comment]
Looking forward for this. 
I recently updated to laravel 5.8 and my composer.json entirely and my test are only failing on this.

**Comment by mikebronner** [comment]
Working on tis now, hope to have a fix out in the next few hours. Writing a test for this scenario, is a bit tricky.

**Comment by mikebronner** [comment]
@lukacavic Can you provide a your complete eloquent model of your User and Books and Link Announcements? I'm having a difficult time recreating the problem.

**Comment by lukacavic** [comment]
Hi, @mikebronner, I will post it tomorow..

Short description:

I have User model, does not use Cachable trait. I also have Announcement model, it uses Cachable trait. I also have a Person model, it does not use Cachable trait. I have link table link_announcement_receivers, that has morphs column "receiver", receiver can be person or user. Becouse announcement can be posted for user or for person. 

Now, in AnnouncementController, when I delete announcement, I also want to detach linked users and linked persons from link table. I use: $announcement->users() - >detach() ; and $announcement->persons() - >detach() ; users() and persons() use morphs relationship. 

When I execute that code to remove persons and users I get error. 

Ok, I will post my code in day or two. 

Thanks

**Comment by Surt** [comment]
It would be great to have the path. I'm stopping the 5.8 update release until the flushCache issue is patched. 

The @lukacavic patch worked for me. Actually is just a typo so I don't know if you need a test for that. Maybe you can merge it?
