### ISSUE TITLE
Publish config

### ISSUE THREAD

**Issue by Tegos** [GeneaLabs/laravel-model-caching#276]
Hello. Have a problem, after upgrade to 0.6, try to run:
`php artisan model-caching:publish --config`
from your documentation
but it doesn't work throws an error:
There are no commands defined in the "model-caching" namespace. 
Maybe it should be php artisan vendor:publish, but there are no publishes in provider.

Another problem: still used _disabled_:
https://github.com/GeneaLabs/laravel-model-caching/blob/master/src/Traits/ModelCaching.php#L45

**Environment**
 - PHP: 7.2.10
 - OS: Windows 10
 - Laravel: 5.8.29
 - Model Caching: 0.6.1

**Comment by mikebronner** [comment]
@Tegos Thanks for submitting this issue. Working on both problems you mentioned right now, should have a fix out shortly.

**Comment by mikebronner** [comment]
This should now be fixed in release 0.6.2. Please let me know how it works for you. Thanks!

**Comment by letinh** [comment]
I have a same issue. I'm using version 0.6.2, laravel 5.8, php version 7.1, may be still this issue.

**Comment by letinh** [comment]
But when I run command: 
```
php artisan model:publish --config
```

It works fine.

**Comment by mikebronner** [comment]
@letinh The correct command is: `php artisan modelCache:publish --config`. I wrote the command incorrectly in the docs. Sorry about that. But you can always list the available artisan commands using `php artisan list` if something isn't working as expected, which shows the correct commands for this package. :)

**Comment by letinh** [comment]
@mikebronner thanks a lot. It works perfect.!!! 👍
