### ISSUE TITLE
Writing Nova Tests

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#283]
If anyone can point me towards some examples of writing tests for nova packages (not apps), I'd be hugely grateful. I'm trying to set up tests for Nova, but am having trouble getting it to run.

https://github.com/GeneaLabs/laravel-model-caching/pull/284

**Comment by nemrutco** [comment]
Let me know if anything i can do for #278 I will try to fix at least this issue.

**Comment by dmason30** [comment]
@mikebronner I think the only way is to have a license. And to use a local auth.json (remember to gitignore) and then on travis use secret env variables:

https://nova.laravel.com/docs/2.0/installation.html#authenticating-nova-in-continuous-integration-ci-environments

It means that any contributors who want to add/fix nova related code would need their own license locally. But one assumes they already have one if requiring changes or fixing bugs related to nova.

I have do use one in a project so am unable to share it but it does mean I should be able to use it locally on any project.

**Comment by mikebronner** [comment]
@dmason30 The license is not the problem :) I have that. The problem is that I have not been able to get unit tests to run.

**Comment by dmason30** [comment]
@mikebronner Ah sorry, I was using the travis error as my basis for the above. Please could you let me know what error you were getting?

**Comment by mikebronner** [comment]
Oh, it's been so long, I don't think I was ever able to figure out how to set up a test case.
