### ISSUE TITLE
Want two apps having same db connection and different cache connection invallidate each other.

### ISSUE THREAD

**Issue by stockarea** [GeneaLabs/laravel-model-caching#285]
Earlier I was using this only on one app and it was working awesome. But now I have made an admin app which also links to the same database. What can I do to make sure the cache gets updated or deleted when any one of them make changes. Will connecting them to same redis cache server will solve this?. Or if there is any other way of implementing cache which I can go along. Any guidance would be of great help.

**Comment by mikebronner** [comment]
Yea, they pretty much have to connect to the same cache for that to work.
