### ISSUE TITLE
Flush single database in multi-tenant application

### ISSUE THREAD

**Issue by roelVerdonschot** [GeneaLabs/laravel-model-caching#287]
When manually flushing the cache all cache is invalidated. It would be useful to only flush the current database connection or have the option to pass a database name.

**Comment by mikebronner** [comment]
@roelVerdonschot thanks for the suggestion. That should be doable, I'll look into it.

**Comment by mikebronner** [comment]
I'm running into problems obtaining a list of all registered tags (needed to flush the cache selectively). Until this is resolved, this feature won't be able to be implemented.

**Comment by mrcageman** [comment]
> When manually flushing the cache all cache is invalidated. It would be useful to only flush the current database connection or have the option to pass a database name.

We're also mighty interested in this feature.

**Comment by roelVerdonschot** [comment]
@mrcageman You can make a script to flush every model one-by-one it's not the most elegant solutions but it works for now.

**Comment by mikebronner** [comment]
Unfortunately clearing cache by database is currently not possible due to driver limitations. I was unable to find a method to list all existing tags for the `redis` and `memcached` drivers. If someone finds a way, please let me know, and I'll be happy to implement it.
