### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by beeyev** [GeneaLabs/laravel-model-caching#293]
Laravel 6 is a new LTS
Could you please implement compatibility with it Laravel 6?

**Comment by mikebronner** [comment]
This has been added for quite a while now.

**Comment by beeyev** [comment]
[https://i.imgur.com/laLjEhP.png](https://i.imgur.com/laLjEhP.png)

**Comment by mikebronner** [comment]
OK, thanks ... that's just a documentation issue, sorry about that.
