### ISSUE TITLE
Support for Laravel 6.1

### ISSUE THREAD

**Issue by hebbet** [GeneaLabs/laravel-model-caching#294]
The current version 0.7 is not installable with Laravel 6.1

Could you release a new version which changes the limit in composer?

**Comment by mikebronner** [comment]
Are you getting composer errors? If so, please post them here. Looking at `composer.json` there should be no issues that I can find off the top. Thanks!

**Comment by hebbet** [comment]
working fine with 0.7.1 when i created that issue, composer didn't show 0.7.1.

**Comment by mikebronner** [comment]
Awesome, thanks for reporting back :)
