### ISSUE TITLE
file_put_contents error

### ISSUE THREAD

**Issue by grcasanova** [GeneaLabs/laravel-model-caching#304]
Fresh larval 6.0 installation on a Mac OS Mojave 10.14.6 with PHP 7.1
When trying to retrieve a model with `Model::all()` with the _Cachable_ trait, it results in a
`file_put_contents(/path/to/storage/framework/cache/data/2c/70/2c707dcbc4c7170cb97cccd70bb8d3aebb20b11e): failed to open stream: No such file or directory`
Path permissions should be already set up. Error happens occasionally with all cached models.

**Comment by mikebronner** [comment]
@grcasanova Please provide the full stack trace an package version. Initially, this seems like a project or server configuration issue. I have not experienced this issue at all, neither in testing nor production.

**Comment by mikebronner** [comment]
Thanks for the stack trace. I don't believe this has anything to do with this plugin, as the error is happening with the cache driver in Laravel. Which cache driver are you using? If you are using the file cache driver, there may be write delays, and other concurrency problems. Those have not been tested, and are largely up to configuration and system performance.

**Comment by padre** [comment]
@mikebronner Yes, I am using the file cache driver. That's probably the reason. In a short time I will switch to redis anad I will be able to check if it stops happening.

 Thanks!

**Comment by grcasanova** [comment]
@mikebronner Does it happen with the _database_ driver too?

**Comment by grcasanova** [comment]
I think the issue is due to the file driver being used and can be closed now
