### ISSUE TITLE
Cache not expiring

### ISSUE THREAD

**Issue by liepumartins** [GeneaLabs/laravel-model-caching#312]
**Describe the bug**
Some records are persisted and not updated/expired in the cache despite a timeout being set.

**Eloquent Query**
With necessary information about the models.
```php
class Item extends Model { 
// not cacheable itself
    public function properties(): HasMany { 
        return $this->hasMany(Property::class);
    }
}

class Property extends Model {
    use Cacheable;
    protected $cacheCooldownSeconds = 300;
    public function value(): BelongsTo {
        return $this->belongsTo(Value::class);
    }
}

@property string name // the database field that keeps getting old values from cache
class Value extends Model {
    use Cacheable;
    protected $cacheCooldownSeconds = 300;
}

// returns $items with old property values. Older than a day or so.
$item->with('properties.value')->find(1);
App\Item { #3132 
  id: 1,
  name: "t3h Item",
  properties: Illuminate\Database\Eloquent\Collection { #3203
    all: [
      App\Value {#3141
        id: 5
        name: "Still old value shown"
      },
     App\Value {#3224
        id: 9
        name: "Another old value"
      },
  }
}

```

I had this problem with more than one model. In one case I disabled caching of `Value` model (removed `Cacheable` trait). In the other case I flushed the cache manually only for the `Value` model with `php artisan modelCache:clear --model=App\\Value`

**Environment**
 - PHP 7.2.24-0ubuntu0.18.04.1
 - OS: Ubuntu 18.04.01 LTS
 - Laravel: 6.9.0
 - Model Caching: 0.7.3
 - memcached 1.5.6

Yes #307 and #308 seem to be related.

**Comment by mikebronner** [comment]
Using `cachecooldown` means that you are preventing the cache from automatically invalidating itself. Is that what you truly wanted to do?

**Comment by liepumartins** [comment]
I see that I have misunderstood the meaning of `cachecooldown`.

The thing is, these tables are (frequently) updated in the database directly via other means. Laravel only reads the data. I do not know, why I was led to believe that `cachecooldown` would be expiration/invalidation time. :man_facepalming: 

So the real question is - how to make cached data invalid every X seconds, to force refresh from database?

**Comment by mikebronner** [comment]
@liepumartins If you need to perform custom cache flushing, don't do it on a timer. Instead, clear the model cache for a specific model when something happens. You can trigger any artisan command from within code: https://laravel.com/docs/6.x/artisan#programmatically-executing-commands. Good luck. :)

**Comment by liepumartins** [comment]
I see that there is option to flush cache manually, I was looking for static method :man_facepalming:    https://github.com/GeneaLabs/laravel-model-caching/blob/aa0253e3a5a6dfc5482b68cb177f50a746c30661/src/Console/Commands/Clear.php#L52

I created options for data updater to call flush, and will monitor how it goes.
