### ISSUE TITLE
Cannot Download

### ISSUE THREAD

**Issue by wtoalabi** [GeneaLabs/laravel-model-caching#318]
I hope I am not the only one experiencing this issue.
on a fresh Laraval 7.0 installation, running `composer require genealabs/laravel-model-caching` 
shows "...could not be fully loaded, package information was loaded from the local cache and may be out of date"
Everything just got stucked from there, please help.

Thanks!

**Comment by mikebronner** [comment]
@wtoalabi Try running
```
composer clear-cache
composer update
```

**Comment by wtoalabi** [comment]
Thanks Mike!
That was pretty fast!!!!

I cleared the cache as suggested and the error changed to: 
[Composer\Downloader\TransportException]
  The "http://repo.packagist.org/p/provider-2013%248857d0ca169e0aaac29ca75c0a31b3edd1b276e80a8f71972fd099fb3e0146b4.json" file could not be downloaded: failed to open stream: HTTP request failed!

**Comment by wtoalabi** [comment]
Fixed!
I needed to run this after: 
`composer config -g repo.packagist composer https://packagist.org`
Then it worked!

Thanks Mike for pointing me in the right direction.

**Comment by mikebronner** [comment]
@wtoalabi Awesome, glad you were able to solve it! :)
