### ISSUE TITLE
relation limit offset

### ISSUE THREAD

**Issue by alexinteam** [GeneaLabs/laravel-model-caching#320]
**Describe the bug**
Found a bug wher using limit, offset in relation

**Qry**

```
Category::with(['posts' => function ($q) use ($offset, $limit) {
                $q->where('active',true)
                    ->orderBy('date', 'DESC')
                    ->offset($offset)
                    ->limit($limit);
            }])
            ->first();
```
so my qry ignored limit, offset totally. 

PS
disabling model caching returns correct data

Thanks.

**Comment by mikebronner** [comment]
Thanks for reporting this! I will try to recreate the issue and see what's going on.

**Comment by mikebronner** [comment]
@alexinteam I was unable to replicate the issue. I created a new test: https://github.com/GeneaLabs/laravel-model-caching/blob/master/tests/Integration/CachedBuilder/WithTest.php#L11

Could you provide a PR with a failing test?

**Comment by alexinteam** [comment]
Sorry, I researched. It wasn't your problem. Closing

**Comment by mikebronner** [comment]
Good to hear! :)
