### ISSUE TITLE
Error in readme MODEL_CACHE_ENABLED vs MODEL_CACHE_DISABLED

### ISSUE THREAD

**Issue by dhcmega** [GeneaLabs/laravel-model-caching#322]
Hi
READMED have `MODEL_CACHE_ENABLED` and `MODEL_CACHE_DISABLED`, but the one actually being used is `MODEL_CACHE_ENABLED`.
Thanks!

**Comment by mikebronner** [comment]
Thanks for the heads-up! Fixed :)
