### ISSUE TITLE
Sustained Laravel 6 (LTS) support

### ISSUE THREAD

**Issue by Harti** [GeneaLabs/laravel-model-caching#341]
**Is your feature request related to a problem? Please describe.**
Laravel 6.x is the current LTS support release (until 2022), but this library abandoned Laravel 6.x starting with 0.8.x.

```
 Problem 1
    - Installation request for genealabs/laravel-model-caching ^0.8.3 -> satisfiable by genealabs/laravel-model-caching[0.8.3].
    - Conclusion: remove laravel/framework v6.18.8
    - Conclusion: don't install laravel/framework v6.18.8
    - genealabs/laravel-model-caching 0.8.3 requires illuminate/http ^7.0
```

**Describe the solution you'd like**
Compatible PRs shall also be merged into 0.7.x releases in order to include bug fixes for Laravel 6.x users. 

**Describe alternatives you've considered**
Alternatively, the dependency tree should be less strict in the composer.json (to allow for usage of Laravel 6.x) - but I'm not sure if this lib does truly require `illuminate/http:^7.0`.

**Additional context**
It is not viable for some users to upgrade to Laravel 7 right now because they are bound to use LTS releases for stability and financial reasons.

**Comment by mikebronner** [comment]
Hi @Harti, thanks for writing in. We will only ever support the current Laravel release. There are various reasons why LTS is a fallacy, which I won't get into here. However, you are welcome to fork the library and make any necessary changes to run on your versions.

**Comment by Harti** [comment]
@mikebronner Would you kindly provide a link that elaborates on your claim of LTS being a _fallacy_? 

I understand your point, but I’d still love to learn about the reasons.

**Comment by mikebronner** [comment]
https://medium.com/@jasonmccreary/laravel-lts-is-a-trap-97b1d1103961
https://connortumbleson.com/2019/01/28/lts-is-a-lie/
https://laracasts.com/discuss/channels/laravel/lts-or-latest-version-which-should-be-used

Google is your friend.

And my reasons:
- it creates too many dependency conditions when maintaining open-source packages.
- you projects loose versatility, as most active packages support the current Laravel version.
- it leads to dead projects, especially when maintaining multiple projects, as the effort to upgrade them to the latest version is delayed, and eventually too much to take on.
- as I don't use LTS versions of Laravel, it would be a waste of my time to try to continue to support it, especially when I don't have projects to test it in.
- writing automated tests for multiple versions of Laravel is a huge increase in complexity, which takes a lot of effort to maintain. I have tried it in the past, and it was never worth it.

I'll be happy to consider sticking to LTS for the right sponsorship level.
