### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by denisdulici** [GeneaLabs/laravel-model-caching#347]
First of all, thanks for the tremendous work done on this package.

Laravel 7 requires PHP 7.2 version. Why don't you respect it?

Why don't you make a **nova-model-caching** package wrapping this one instead of removing features general Laravel users?

**Comment by denisdulici** [comment]
Furthermore, such a critical change is done in a patch version and suddenly our [software](https://github.com/akaunting/akaunting) failed due to it.

**Comment by mikebronner** [comment]
Hi @denisdulici, thanks for writing in. You are absolutely right about the PHP version. I went ahead and adjusted that. Please try release 0.8.5 and let me know how that works for you.

I'm not sure I understand you second point about Nova? No functionality is being removed to accommodate Nova. We are adding additional tests to make sure it works with Nova.

**Comment by mikebronner** [comment]
> Furthermore, such a critical change is done in a patch version and suddenly our [software](https://github.com/akaunting/akaunting) failed!

Can you elaborate which patch broke what?

**Comment by denisdulici** [comment]
In fact, it doesn't break any feature, yet. However, it doesn't pass [tests](https://github.com/akaunting/akaunting/runs/639279793).

As for Nova, it [seems](https://github.com/GeneaLabs/laravel-model-caching/commit/d5c930af6790447841d298891f3dd7799b7080c1) you changed it for the sake of Nova. That's why I thought that if it's required for Nova, why not create a new package?

**Comment by denisdulici** [comment]
Woohoo, just saw the fix release. Thanks for the prompt response 😉

**Comment by mikebronner** [comment]
I'm also updating our own tests to include different PHP versions now in actions.

**Comment by mikebronner** [comment]
Going to close this for now, assuming everything is good on your end?

**Comment by denisdulici** [comment]
Yep, it worked fine, thanks again.
