### ISSUE TITLE
PHP 7.2 action not actually working

### ISSUE THREAD

**Issue by dmason30** [GeneaLabs/laravel-model-caching#348]
https://github.com/GeneaLabs/laravel-model-caching/blob/7e7f527b0e845ab410c78324de5af7e31f61f993/.github/workflows/laravel.yml#L17

The setup php action does not support characters in the version provided from the matrix.

https://github.com/GeneaLabs/laravel-model-caching/blob/7e7f527b0e845ab410c78324de5af7e31f61f993/.github/workflows/laravel.yml#L33

This is resulting in this ⚠️ _silent_ ⚠️  error:

![image](https://user-images.githubusercontent.com/20278756/80896750-9dbe8980-8ce9-11ea-9ac3-898f9aa10a70.png)
https://github.com/GeneaLabs/laravel-model-caching/runs/639471767?check_suite_focus=true#step:6:9

So this is actually running tests on 7.4 (i think).

This should be changed to 

```yml
php: [7.2, 7.3, 7.4]
```

**Note:** There is no way to force it to install a particular patch version of PHP at this time and you shouldn't need to?

**Comment by mikebronner** [comment]
Closing this, as I have come to a decision to no longer support PHP 7.2 going forward.
