### ISSUE TITLE
When insert a new record, I fecth an error

### ISSUE THREAD

**Issue by RonnieCSE** [GeneaLabs/laravel-model-caching#353]
`
Code

 $data_insert = array(
        'video_id' => 1,
        'user_id' => 1
)
     App\Video::withCacheCooldownSeconds(20)->create($data_insert);`

![image](https://user-images.githubusercontent.com/22654265/82323732-4ebb6880-99fa-11ea-8bc2-8ed9376de54e.png)

**Comment by mikebronner** [comment]
@RonnieCSE Please provide the full stack trace when reporting errors.
