### ISSUE TITLE
Trait method 'newBelongsToMany' will not be applied, because it collides with 'ExtendRelationsTrait'

### ISSUE THREAD

**Issue by smartssa** [GeneaLabs/laravel-model-caching#354]
**Describe the bug**
It's a strange phpStorm code linter warning that makes me think something with relations may not work as expected.

When implementing a `use Cachable` in my model:
"Trait method 'newBelongsToMany' will not be applied, because it collides with 'ExtendRelationsTrait'"

**Environment**
 - PHP: 7.4.6
 - phpStorm 2020.1.2
 - OS: macOS Catalina
 - Laravel: 7.14.1
 - Model Caching: 0.8.6

**Additional context**
Could be a non-issue.

**Comment by smartssa** [comment]
Not that I am aware of, I will investigate.

**Comment by mikebronner** [comment]
Would you mind doing a global search for `ExtendRelataionsTrait` in your code and vendor files to see where this exists?

**Comment by smartssa** [comment]
Only mentions are:
/laravel-pivot-events/src/Traits/ExtendRelationsTrait.php
/laravel-pivot-events/src/Traits/PivotEventTrait.php

Found a few issues on JetBrains:
https://youtrack.jetbrains.com/issue/WI-53153
https://youtrack.jetbrains.com/issue/WI-53171

**Comment by mikebronner** [comment]
Ah! Perfect :) whew
