### ISSUE TITLE
Can't install 0.8.4 in laravel 6.18.20

### ISSUE THREAD

**Issue by jkhaoqi110** [GeneaLabs/laravel-model-caching#357]
**Describe the bug**
Laravel-model-caching 0.8.4 is not compatible with laravel 6.18.20, The document says support laravel 6.0+, but the error appeared when I installed the version 0.8.4.

**Stack Trace**
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: genealabs/laravel-pivot-events[0.3.0, 0.2.1].
    - Can only install one of: genealabs/laravel-pivot-events[0.3.0, 0.2.1].
    - Can only install one of: genealabs/laravel-pivot-events[0.3.0, 0.2.1].
    - genealabs/laravel-model-caching 0.8.4 requires genealabs/laravel-pivot-events ^0.3.0 -> satisfiable by genealabs/laravel-pivot-events[0.3.0].
    - Installation request for genealabs/laravel-model-caching 0.8.4 -> satisfiable by genealabs/laravel-model-caching[0.8.4].
    - Installation request for genealabs/laravel-pivot-events (locked at 0.2.1, required as *) -> satisfiable by genealabs/laravel-pivot-events[0.2.1].


Installation failed, reverting ./composer.json to its original content.
```

**Environment**
 - PHP: 7.4.5
 - OS: Windows 10
 - Laravel: 6.18.20
 - Model Caching: 0.8.4

**Comment by mikebronner** [comment]
Hi @jkhaoqi110 , this package is no longer compatible with Laravel 6.x, it requires Laravel 7.x. The readme has stated this for some time. Where do you see it documented to support Laravel 6? Please let me know so I can correct the documentation. Thanks!

**Comment by jkhaoqi110** [comment]
> Hi @jkhaoqi110 , this package is no longer compatible with Laravel 6.x, it requires Laravel 7.x. The readme has stated this for some time. Where do you see it documented to support Laravel 6? Please let me know so I can correct the documentation. Thanks!

https://github.com/GeneaLabs/laravel-model-caching/tree/0.8.4
![image](https://user-images.githubusercontent.com/7346148/85350453-c453b080-b533-11ea-8ea6-40031457ebbd.png)

**Comment by mikebronner** [comment]
Thanks @jkhaoqi110, the readme has been updated for some time in the repo.
