### ISSUE TITLE
issue with "Cachable:applyScopes() : self" not compatible with "Eloquent\Builder::applyScopes()"

### ISSUE THREAD

**Issue by olivM** [GeneaLabs/laravel-model-caching#359]
`Declaration of GeneaLabs\LaravelModelCaching\Traits\Cachable::applyScopes(): GeneaLabs\LaravelModelCaching\Traits\Cachable must be compatible with App\Models\Teaching::applyScopes(): App\Models\Teaching`

seems the newly added applyScopes with return type hinting is causing a problem

**Comment by mikebronner** [comment]
Will fix ASAP ... wonder why that didn't show when testing. Might need to add another test.

**Comment by mikebronner** [comment]
@olivM can you try release 0.8.8? Should be fixed now.

**Comment by olivM** [comment]
same error with 0.8.8
Caching::applyScopes() hasn't changed : https://github.com/GeneaLabs/laravel-model-caching/blob/master/src/Traits/Caching.php#L35

**Comment by mikebronner** [comment]
Lordie! I forgot to push my commits. Try 0.8.9. Thanks for letting me know!
