### ISSUE TITLE
PivotEventTrait method not applied

### ISSUE THREAD

**Issue by Tjab** [GeneaLabs/laravel-model-caching#361]
**Describe the bug**
My PHPStorm shows an error:

![image](https://user-images.githubusercontent.com/6023513/87292898-c9d46300-c501-11ea-85aa-83d61186b81c.png)

**Environment**
 - PHP: [e.g. 7.3.0]
 - OS: Homestead (newest)
 - Laravel: 7.16.1
 - Model Caching: 0.8.6

**Additional context**
Shouldn't be my problem to fix right? As soon as I place (in my class that uses the Cachable trait):

```
protected function newBelongsToMany(Builder $query, Model $parent, $table, $foreignPivotKey, $relatedPivotKey, $parentKey, $relatedKey, $relationName = null)
{
}
```

It's fixed, but I believe it should be fixed in the trait itself?

**Comment by mikebronner** [comment]
@Tjab could you provide your model code for review? Thanks!

**Comment by Tjab** [comment]
@mikebronner sure, but now you make me doubt as to if it's something that I'm doing wrong! Haha :)

As soon as I create a class and use the trait, the error shows.

```php
<?php

namespace app\Models;

use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use Illuminate\Database\Eloquent\Model;

class ExampleClass extends Model
{
    use Cachable;
}
```

![image](https://user-images.githubusercontent.com/6023513/87310272-08781680-c51e-11ea-827f-f222087d8558.png)

**Comment by mikebronner** [comment]
@Tjab Thanks for the update! :) I will take a look, but am wondering if it isn't a bug in PHPStorm, as I haven't had this error show up when running code.

**Comment by mikebronner** [comment]
Revisiting the code, I think its a PHPStorm bug. There are only two places this function exists in regard:
- `laravel-pivot-events/src/traits/ExtendRelationsTrait.php`
- `Laravel-model-caching/src/Traits/ModelCaching.php`

However, in `Cachable` we are overriding the method from `laravel-pivot-events` to use the one from  `ModelCaching`. I believe it is this that PHPStorm has issue with interpreting correctly:
```php
    use PivotEventTrait {
        ModelCaching::newBelongsToMany insteadof PivotEventTrait;
    }
```

All tests pass without any errors when running the code, so it's likely something other than the code in this case. I'll close for now. Thanks for bringing this up, I hadn't seen this before, as I don't use PHPStorm anymore.

**Comment by Tjab** [comment]
Thanks for the work/help! I've reported it at PHPStorm :) Hopefully they can fix it easily, it's very annoying! Thanks again!

**Comment by mikebronner** [comment]
@Tjab Good luck! Let me know what they say. :) Thanks :)
