### ISSUE TITLE
Cannot use 'DEL' with redis-cluster.

### ISSUE THREAD

**Issue by Nowi5** [GeneaLabs/laravel-model-caching#364]
**Describe the bug**
Expected: Clearing the cache across the packages of Laravel (Symfony) and Predis should work with AWS Redis Cluster.

![image](https://user-images.githubusercontent.com/27913135/89125807-52cb3280-d4e1-11ea-832b-d9234d48140a.png)

**Eloquent Query**
Please provide the complete eloquent query that caused the bug, for example:
```php
$model->with('otherModel')->get();
```

**Stack Trace**
The full stack trace from your log file.

**Environment**
 - PHP: >=7.2.5
 - OS: Windows 10 + Docker -> Debian / AWS Latest PHP Elastic Beanstalk
 - Laravel: 7.22.4
 - Model Caching: 0.9.0

**Additional context**
have the same issue local and on AWS.
Config database.php

```

'redis' => [
        'client' => 'predis',
        'cluster' => env('REDIS_CLUSTER', false),
        'options' => [
            'cluster' => 'redis',
            'parameters' => [
                'password' => env('REDIS_PASSWORD', null),
                'scheme' => env('REDIS_SCHEME', 'tcp'),
                ],
            'ssl' => ['verify_peer' => false]
        ],
        'clusters' => [
            'default' => [
                [
                    'scheme'   => env('REDIS_SCHEME', 'tcp'),
                    'host' => env('REDIS_HOST', 'localhost'),
                    'password' => env('REDIS_PASSWORD', null),
                    'port' => env('REDIS_PORT', 6379),
                    'database' => env('REDIS_DATABASE', 0),
                ],
                'options' => [
                    // Clustering specific options
                    'cluster' => 'redis',
                    // This tells Redis Client lib to follow redirects (from cluster)
                ]
            ],
            // duplicate of default
            'cache' => [
                [
                    'scheme'   => env('REDIS_SCHEME', 'tcp'),
                    'host' => env('REDIS_HOST', 'localhost'),
                    'password' => env('REDIS_PASSWORD', null),
                    'port' => env('REDIS_PORT', 6379),
                    'database' => env('REDIS_DATABASE', 0),
                ],
                'options' => [
                    // Clustering specific options
                    'cluster' => 'redis',
                    // This tells Redis Client lib to follow redirects (from cluster)
                ]
            ],
        ],
    ],

```

Using a AWS Redis Cluster with 3 nodes. Any idea where to start to debug?

**Comment by mikebronner** [comment]
Hi @Nowi5, thanks for writing in about this issue. This would almost certainly be an issue with Predis and AWS not being compatible with each other. This package just provides a functional layer on top of Laravel's caching mechanism. I would file a bug with Predis with a complete StackTrace and go from there. Please do keep me informed of your developments, in case I need to make any updates here. Best of luck!

**Comment by Nowi5** [comment]
I have the same issues when using my local docker including redis. Let see if the Laravel Community can help:
https://github.com/laravel/framework/issues/33733

**Comment by mikebronner** [comment]
@Nowi5 Awesome, looks like you got all bases covered. I subscribed to your two other tickets and will follow along to see what comes of it. :)

**Comment by Nowi5** [comment]
@mikebronner Thank you for your support as always. Found a temporary solution back from 2017. Do you have any deeper insights to judge if that change makes actually sense? Thank you for your expert opinion.

**Comment by mikebronner** [comment]
@Nowi5  My recommendation would be to switch to PHPREDIS, as that is the recommended path forward by Laravel, I believe.

**Comment by mikebronner** [comment]
I'm going to work on a release that removes the predis dependency.

**Comment by mikebronner** [comment]
@Nowi5 Please give release 0.10.0 a try with PHPRedis and let me know how it goes.
