### ISSUE TITLE
Am I missing something obvious?

### ISSUE THREAD

**Issue by mbuk** [GeneaLabs/laravel-model-caching#37]
# Issue
I have a model BannedIp - it extends CachedModel
When I delete a record using
BannedIp::where('id', 1)->delete();
The cache is not updated

Using a redis for my cache

```
namespace App;

use GeneaLabs\LaravelModelCaching\CachedModel;

class BannedIp extends CachedModel
{

}

```

It appears as if 
```
static::deleted(function () use ($instance) {
            $instance->flushCache();
        });
```
in CachedModel.php is never hit

**I'm trying a fresh install of laravel with a single model now to see if it's something specific to my laravel env**

## Environment
Laravel Version: *5.5.5*
Laravel Model Caching Package Version: *0.2.10*
PHP Version: *7.1.10*
Homestead Version: N/A
Operating System & Version: OSX High Sierra 10.13.1

**Comment by mikebronner** [comment]
Thanks for reporting this!! I will work on this ASAP, should have an update to you within the next 24 hours.

**Comment by mbuk** [comment]
Thanks @mikebronner let me know if I can help!

**Comment by mbuk** [comment]
@mikebronner a bit more info it if helps.  Testing on a fresh install.  If I do this
``` App\Testing::first()->delete(); ```
The cache is cleared and ``` static::deleted ``` in CachedModel is hit

I think this might be expected behaviour from eloquent: see [https://github.com/laravel/framework/issues/2536](https://github.com/laravel/framework/issues/2536)

**Comment by mikebronner** [comment]
Thanks :) Just released v0.2.11 that should fix this. Let me know how it works. Closing issue for now, please re-open if you find some weirdness. :)

**Comment by mbuk** [comment]
Works like a charm - thanks @mikebronner 👍

**Comment by mikebronner** [comment]
Awesome! :) Thanks for reporting it, please submit any other oddities you find as well! :)
