### ISSUE TITLE
Nonexistent class EloquentBuilder

### ISSUE THREAD

**Issue by webard** [GeneaLabs/laravel-model-caching#376]
Hello,
I ran Rector on my application and one of problem is:
` [ERROR] Could not process "app/Abilities/Taxonable.php" file, due to:                                                  
         "Analyze error: "Class GeneaLabs\LaravelModelCaching\EloquentBuilder not found.". Include your files in        
         "parameters > autoload_paths".                                                                                 
         See https://github.com/rectorphp/rector#configuration".   `

https://github.com/GeneaLabs/laravel-model-caching/blob/ce98454c64904bbc57d04a0a9265e376e37e8093/src/Traits/ModelCaching.php#L5

**Comment by danijelmaric** [comment]
+1

**Comment by anilkr143** [comment]
Hi @mikebronner, I am not able to use this package latest version 0.11.1 due to class EloquentBuilder not found issue. Please fix this.

**Comment by mikebronner** [comment]
@webard  Looking at this again, this is not a bug. `EloquentBuilder` is a class alias defined in the service provider. The errors you are seeing are likely a limitation of the code analyzer.

@anilkr143 Please provide a full stack trace if you are seeing errors.

**Comment by danijelmaric** [comment]
Error : Class 'GeneaLabs\LaravelModelCaching\EloquentBuilder' not found
 /Users/danijelmaric/www/play_engine/vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php:105
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1183
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1219
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1172
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1885
 /Users/danijelmaric/www/play_engine/vendor/genealabs/laravel-model-caching/src/Traits/Caching.php:22
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1897
 /Users/danijelmaric/www/play_engine/src/Core/Console/SeedCountries.php:43
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/Container.php:610
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Command/Command.php:255
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Application.php:971
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Application.php:290
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Application.php:166
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Application.php:93
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Application.php:185
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:263
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
 /Users/danijelmaric/www/play_engine/database/migrations/2020_01_03_104733_create_global_countries_table.php:25
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:392
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:400
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:200
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:165
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:110
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:85
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:541
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:94
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/Container.php:610
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Command/Command.php:255
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php:68
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php:28
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/FreshCommand.php:55
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Container/Container.php:610
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Command/Command.php:255
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Application.php:971
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Application.php:290
 /Users/danijelmaric/www/play_engine/vendor/symfony/console/Application.php:166
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Application.php:93
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Console/Application.php:185
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:263
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:207
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:390
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:66
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Foundation/Testing/RefreshDatabase.php:65
 /Users/danijelmaric/www/play_engine/vendor/laravel/framework/src/Illuminate/Foundation/Testing/RefreshDatabase.php:18
 /Users/danijelmaric/www/play_engine/vendor/orchestra/testbench-core/src/Concerns/Testing.php:154
 /Users/danijelmaric/www/play_engine/vendor/orchestra/testbench-core/src/Concerns/Testing.php:252
 /Users/danijelmaric/www/play_engine/vendor/orchestra/testbench-core/src/Concerns/Testing.php:160
 /Users/danijelmaric/www/play_engine/vendor/orchestra/testbench-core/src/TestCase.php:65
 /Users/danijelmaric/www/play_engine/vendor/orchestra/testbench-core/src/Concerns/Testing.php:83
 /Users/danijelmaric/www/play_engine/vendor/orchestra/testbench-core/src/TestCase.php:43
 /Users/danijelmaric/www/play_engine/tests/Traits/PlayEngineSetupTest.php:36

**Comment by anilkr143** [comment]
local.ERROR: Class 'GeneaLabs\LaravelModelCaching\EloquentBuilder' not found {"exception":"[object] (Error(code: 0): Class 'GeneaLabs\\LaravelModelCaching\\EloquentBuilder' not found at F:\\Programs\\wamp\\www\\trackerapi\\vendor\\genealabs\\laravel-model-caching\\src\\Traits\\ModelCaching.php:105)
[stacktrace]
#0 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\database\\Eloquent\\Model.php(1182): App\\Models\\Model->newEloquentBuilder(Object(Illuminate\\Database\\Query\\Builder))
#1 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\database\\Eloquent\\Model.php(1218): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#2 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\database\\Eloquent\\Model.php(1171): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#3 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\database\\Eloquent\\Model.php(1884): Illuminate\\Database\\Eloquent\\Model->newQuery()
#4 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\genealabs\\laravel-model-caching\\src\\Traits\\Caching.php(22): Illuminate\\Database\\Eloquent\\Model->__call('where', Array)
#5 F:\\Programs\\wamp\\www\\trackerapi\\app\\Models\\User.php(171): App\\Models\\Model->__call('where', Array)
#6 F:\\Programs\\wamp\\www\\trackerapi\\app\\Http\\Controllers\\UserController.php(377): App\\Models\\User->getUserByMobile('9015556022', 1)
#7 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\container\\BoundMethod.php(36): App\\Http\\Controllers\\UserController->login(Object(Dingo\\Api\\Http\\Request))
#8 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#11 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#12 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(386): Illuminate\\Container\\Container->call(Array, Array)
#13 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(352): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#14 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(326): Laravel\\Lumen\\Application->callLumenController(Object(App\\Http\\Controllers\\UserController), 'login', Array)
#15 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(279): Laravel\\Lumen\\Application->callControllerAction(Array)
#16 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(259): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#17 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Dingo\\Api\\Http\\Request))
#18 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(48): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))
#19 F:\\Programs\\wamp\\www\\trackerapi\\app\\Http\\Middleware\\Localization.php(24): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))
#20 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): App\\Http\\Middleware\\Localization->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#21 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#22 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))
#23 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\dingo\\api\\src\\Http\\Middleware\\PrepareController.php(45): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))
#24 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#25 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#26 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))
#27 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))
#28 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(423): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(260): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#30 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(234): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#31 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(170): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)
#32 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Dingo\\Api\\Http\\Request))
#33 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(48): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))
#34 F:\\Programs\\wamp\\www\\trackerapi\\app\\Http\\Middleware\\RequestLogger.php(41): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))
#35 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): App\\Http\\Middleware\\RequestLogger->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#36 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#37 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(30): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))
#38 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))
#39 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(423): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(172): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#41 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Lumen.php(116): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))
#42 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\dingo\\api\\src\\Routing\\Router.php(518): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')
#43 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))
#44 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(128): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))
#45 F:\\Programs\\wamp\\www\\trackerapi\\app\\Http\\Middleware\\TrimStrings.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#46 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): App\\Http\\Middleware\\TrimStrings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#47 F:\\Programs\\wamp\\www\\trackerapi\\app\\Http\\Middleware\\DecryptStrings.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#48 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): App\\Http\\Middleware\\DecryptStrings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#49 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#50 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#51 F:\\Programs\\wamp\\www\\trackerapi\\app\\Http\\Middleware\\RequestLogger.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#52 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): App\\Http\\Middleware\\RequestLogger->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#53 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#54 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))
#56 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#57 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#58 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(30): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))
#59 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\illuminate\\pipeline\\Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#60 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(423): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(172): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#62 F:\\Programs\\wamp\\www\\trackerapi\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(109): Laravel\\Lumen\\Application->dispatch(NULL)
#63 F:\\Programs\\wamp\\www\\trackerapi\\public\\index.php(28): Laravel\\Lumen\\Application->run()
#64 {main}
"}
