### ISSUE TITLE
Doesn't cache data

### ISSUE THREAD

**Issue by damian-g** [GeneaLabs/laravel-model-caching#378]
# Issue
I am trying to run cache, but no effects. After first run of test model I have only these keys on Redis db:
1) "crm_database_crm_cache:cbb55910ff99021b65728bc3621625ee08e71a32:0fa880c7deb3f44d834e0684c680bdeca5c1dba8"
2) "crm_database_crm_cache:ade548970c7483b83c9b362d314e6c3e29c55325:timer"
3) "crm_database_crm_cache:5f81f4b449141558210699:forever_ref"
4) "crm_database_crm_cache:ade548970c7483b83c9b362d314e6c3e29c55325"
5) "crm_database_crm_cache:tag:genealabs:laravel-model-caching:mysql:mauth:app-crm-modelsclientdata:key"

There is no more keys with data, which are in mysql db. Can anyone paste working example?

## Environment
Laravel Version: *8.9.0*
Laravel Model Caching Package Version: *0.11.0*
PHP Version: *7.4.10*
Homestead Version: *x.y*
Operating System & Version: *Debian 9.13*

**Comment by mikebronner** [comment]
Hi Damiang, please take the time to fill out the full bug report. I need stack trace, all involved eloquent queries, any relevant config files, and any relevant `.env` settings.
