### ISSUE TITLE
Declaration of Cachable::newBelongsToMany should be compatible with Model::newBelongsToMany

### ISSUE THREAD

**Issue by harrisdt15f** [GeneaLabs/laravel-model-caching#380]
**Describe the bug**
I got the below error when I installed on laravel 8.

 `Warning: Declaration of GeneaLabs\LaravelModelCaching\Traits\Cachable::newBelongsToMany(GeneaLabs\LaravelModelCaching\EloquentBuilder $query, Illuminate\Database\Eloquent\Model $parent, $table, $foreignPivotKey, $relatedPivotKey, $parentKey, $relatedKey, $relationName = NULL) should be compatible with Illuminate\Database\Eloquent\Model::newBelongsToMany(Illuminate\Database\Eloquent\Builder $query, Illuminate\Database\Eloquent\Model $parent, $table, $foreignPivotKey, $relatedPivotKey, $parentKey, $relatedKey, $relationName = NULL) in /var/www/jianghu_entertain/app/Models/BaseModel.php on line 14`

![image](https://user-images.githubusercontent.com/27404296/96615598-0f3fd200-1334-11eb-8530-866672ffb4f7.png)
![image](https://user-images.githubusercontent.com/27404296/96615624-1961d080-1334-11eb-9816-47fd43f16999.png)

**Environment**
 - PHP: 7.4.11
 - OS: Ubuntu 18.04
 - Laravel: 8.10.0
 - Model Caching: 0.11.0

**Additional context**
![image](https://user-images.githubusercontent.com/27404296/96615283-a5bfc380-1333-11eb-9159-dc29a6085e79.png)

**Comment by mikebronner** [comment]
Hi @harrisdt15f, just curious, why did you close this? I want to make sure I have everything covered.

Thanks :)
