### ISSUE TITLE
Is there a way to use this framework with Laravel 5.8?

### ISSUE THREAD

**Issue by jberu624** [GeneaLabs/laravel-model-caching#388]
**Is your feature request related to a problem? Please describe.**
Hi i'm trying to to implement this framework but my version of laravel is 5.8 and can't upgrade right now for business reasons. Is there a way to get composer to use a version of the code that works with 5.8?

**Describe the solution you'd like**
I would like to be able to use the framework on laravel 5.8

**Comment by mikebronner** [comment]
Hi @jberu624, unfortunately your version of Laravel is no longer supported.
