### ISSUE TITLE
Default to Laravel File cache if server cache is down

### ISSUE THREAD

**Issue by oulfr** [GeneaLabs/laravel-model-caching#392]
When server is down it's better to use laravel file cache as default.

https://stackoverflow.com/questions/28047861/default-to-laravel-file-cache-if-redis-is-down

**Comment by oulfr** [comment]
Better implementation:

https://github.com/oulfr/laravel-cache-fallback

**Comment by mikebronner** [comment]
Hi @oulfr, thanks for the suggestions. These are all things that should be implemented by the app developer. I don't want to make any presumptions.
