### ISSUE TITLE
Can this use the Octane Cache?

### ISSUE THREAD

**Issue by jcsoriano** [GeneaLabs/laravel-model-caching#404]
**Is your feature request related to a problem? Please describe.**
Laravel Octane Cache makes use of Swoole tables that can support up to 2,000,000 operations per second. Does this package support it?

**Describe the solution you'd like**
Support using the Octane cache for model caching

**Comment by jcsoriano** [comment]
For anyone who sees this in the future - I tried it with the Laravel Octane cache and it works!

Thanks for the package!

**Comment by mikebronner** [comment]
@jcsoriano Thank you for verifying! :) Good to hear.
