### ISSUE TITLE
Lighthouse (GraphQL) compatibility

### ISSUE THREAD

**Issue by binaryfire** [GeneaLabs/laravel-model-caching#410]
Hi guys,

Just wondering if model caching works with Lighthouse? I'm hoping this could sit underneath Lighthouse so GraphQL queries hit the model cache instead of the db....

Thanks!

**Comment by webard** [comment]
Lighthouse using eloquent models. It works with model caching without any additional configuration.

**Comment by mikebronner** [comment]
@binaryfire This works as long as you are using Lighthouse for your data store, and not as your cache store. What @webard said. :)

**Comment by binaryfire** [comment]
Great, thanks guys!
