### ISSUE TITLE
i hvae issule in cache in tenancyforlaravel package

### ISSUE THREAD

**Issue by vahidalvandi** [GeneaLabs/laravel-model-caching#412]
i use laravel 8 and last version of this package . i have saas server but cache not work . each user have one db and i dont now how set cache for each tanent

https://tenancyforlaravel.com/

**Comment by mikebronner** [comment]
Hi @vahidalvandi, I'm not familiar with that tenancy package, but am happy to consider any PRs that would update documentation that describes how to set up this package in conjunction with that one, in addition to any PRs that will make any necessary changes to this package.

**Comment by vahidalvandi** [comment]
tenancyforlaravel.com is nice and powerful in tenancy . and i dont now stracure laravel-model-caching .
