### ISSUE TITLE
cache for request validation to avoid searching in db everytime make request.

### ISSUE THREAD

**Issue by harrisdt15f** [GeneaLabs/laravel-model-caching#413]
if a request make from request validtion ,it check the data if it is exist in db everyonce. for some config table data, if it is able to make cache to avoid every request hit to the db.

**Comment by mikebronner** [comment]
Hi @harrisdt15f, I'm not sure if I understand your request correctly -- do I understand it correctly that you are asking for caching of Laravel validations that access the database? If that is the case, unfortunately that is outside of the scope of this project.
(If I misunderstood your request, please reopen this issue and explain in more detail, perhaps with an example.)

Thanks for writing in. :)
