### ISSUE TITLE
add cache driver option in abstract class

### ISSUE THREAD

**Issue by rssawhney** [GeneaLabs/laravel-model-caching#42]
# Issue
using different cache driver for model caching other than the app specific cache driver

## Environment
Laravel Version: *5.5.25*
Laravel Model Caching Package Version: *0.2.12*
PHP Version: *7.1.11*

Operating System & Version: *Ubuntu 16.04*

**Comment by mikebronner** [comment]
If you are configuring caching outside of Laravel, then this package probably isn't for your use case. This package specifically uses the cache driver configured in the app configuration, and is not meant to be used with external caching services.

If you do have the cache driver configured in the laravel config files, please reopen this issue and provide more details as to what problems you are having. Thanks for trying this package out, and good luck on your project! :)

**Comment by rssawhney** [comment]
I am configuring cache inside laravel only, I am using 1 redis instance and 1 memcached. Where memcached one is defined in .env as CACHE_DRIVER. 

This package is using the memcached driver for caching. I want to use the redis as caching driver that's why I was asking to add a custom driver option.

Something like this package https://github.com/dwightwatson/rememberable#cache-driver

**Comment by mikebronner** [comment]
HI @rssawhney thanks for following up with more details. I see now what you mean: you have two Laravel cache drivers defined, and want a way to specify which one to use. That makes sense! I will look into that. Thanks for the clarifying your use-case, that makes a lot of sense to add that ability to this package.

**Comment by mikebronner** [comment]
Just released version 0.2.13, please let me know if that fixes your issue. :)

Thanks!
