### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by fulopattila122** [GeneaLabs/laravel-model-caching#422]
Hi There,

First of all thanks for this package, I've been using such solutions with Symfony/Doctrine and other homegrown variants for years and I missed this from Laravel, so it's great to have it :+1: 

To improve the predictability of the package changes across packages, I suggest using Semantic Versioning: https://semver.org
The site describes it in detail, but it is actually very simple and can be summarized in a few lines:

> Given a version number MAJOR.MINOR.PATCH (eg. 2.1.1), increment the:
>
>    MAJOR version when you make incompatible API changes,
>    MINOR version when you add functionality in a backward-compatible manner, and
>    PATCH version when you make backward-compatible bug fixes.

Composer itself also supports semantic versioning: https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators and I believe it would be a simple and great thing to follow semver.

As a concrete example, the latest release (as of writing this) was `0.12.1` and since it contains an "`Added`` line in the changelog, it is should be `0.13.0`.

If you think it's a good idea, I'd be happy to add it to the README - it doesn't require tools, it's similar to the "keep a changelog" convention.

**Comment by mikebronner** [comment]
We are using semantic versioning. It is still in beta, hence the `0.x`

**Comment by fulopattila122** [comment]
I didn't refer to `0.x` but to the fact that according to semantic versioning if you **add** a functionality, you need to increase the MINOR version number. Whereas in this release, functionality has been added and the PATCH has been increased:

![image](https://user-images.githubusercontent.com/1162360/155970179-270a2b9b-edd3-4d11-9538-fb277d47304e.png)
