### ISSUE TITLE
Clear cache in a record of the model.

### ISSUE THREAD

**Issue by Jesus-Rojas** [GeneaLabs/laravel-model-caching#436]
Hi good day, wanted to disturb @mikebronner.

`Pivot::updating(function ($pivot) { $source = new Source; $source->flushCache(); });`

How to clean a record of the model without to clean all model, currently it was solved with method flush but this clean all cache of model.

Thanks!!

**Comment by mikebronner** [comment]
Hi @Jesus-Rojas, that is by design, there is no other feasible way to partially clear the cache for a model.

**Comment by Jesus-Rojas** [comment]
I understand, thanks so much @mikebronner .
