### ISSUE TITLE
Laravel v10.3.0 breaks LaravelModelCaching

### ISSUE THREAD

**Issue by Bjornftw** [GeneaLabs/laravel-model-caching#445]
**Describe the bug**
Laravel v10.3.0 is using an updated version of paginate().

```Declaration of GeneaLabs\LaravelModelCaching\Traits\Buildable::paginate($perPage = null, $columns = [...], $pageName = 'page', $page = null) must be compatible with Illuminate\Database\Eloquent\Builder::paginate($perPage = null, $columns = [...], $pageName = 'page', $page = null, $total = null)```

**Environment**
 - PHP: 8.2
 - Laravel: v10.3.0
 - Model Caching: 0.13.1

**Comment by faytekin** [comment]
https://github.com/laravel/framework/pull/46336 happens because of the change made here.

**Comment by Bjornftw** [comment]
Fixed in 0.13.2 [(https://github.com/GeneaLabs/laravel-model-caching/commit/1fe37744efa9d5ed3d8c245c68271022b0e452ab) https://github.com/GeneaLabs/laravel-model-caching/releases/tag/0.13.2 ](https://github.com/GeneaLabs/laravel-model-caching/commit/1fe37744efa9d5ed3d8c245c68271022b0e452ab)
