### ISSUE TITLE
Optimize Cache Keys

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#48]
Currently cache keys can be extraordinarily long, which might cause an issue if max key length is reached.

To prevent this, I had the idea of generating cache keys the same way they are now, but then using their hash as the key.

This will reduce key size, as well as obfuscate its content. (That would only be important for encrypted data, which it currently is not, but could also be a future consideration.)

I could see this being a quick little project for you. Please let me know your thoughts on the concept (pros/cons), and if you would be interested in it.

**Comment by sjbronner** [comment]
Before starting, it might be a good idea to see what the underlying cache stores do with the key. Some may already be hashing it. Here are the results of that check:

* apc: the passed key is combined with a prefix and then used as the final key without any hashing
* array: the passed key used as the final key without hashing or any other supplemental data
* database: the passed key is combined with a prefix and then used as the final key without any hashing
* file: the passed key is sha1-hashed and used as the filename containing the serialized object
* memcached: the passed key is combined with a prefix and then used as the final key without any hashing
* redis: the passed key is combined with a prefix string and a sha1-hashed namespace and then used as the final key

**Comment by sjbronner** [comment]
Choosing a hashing function:

The key hash must not be salted and it has no security implications. SHA1 is fast and has a good collision resistance. It is also widely used when caching. It seems to be a good choice.

For a comparison of hash function properties, see: https://en.wikipedia.org/wiki/SHA-2#Comparison_of_SHA_functions

**Comment by mikebronner** [comment]
Implemented in release 0.2.18.
