### ISSUE TITLE
Clear Cache Before Every Test

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#55]
It has come to light that some tests are squeaking by and passing because of existing cache entries. We have fixed this where found, but will address this as a whole, so that we can check with confidence that this doesn't occur anywhere else.

**Comment by sjbronner** [comment]
Aren't all existing cache entries cleared at the end of `setUp()` by `cache()->flush()`?

**Comment by mikebronner** [comment]
Ah yes, you're right. I forgot about that. So then why do you think we were getting false positives?

**Comment by sjbronner** [comment]
Maybe it's not working. Can you tell me what code is run by that call?

**Comment by sjbronner** [comment]
Looking at an example of a false positive result gave me further insight into the issue:
`tests/Unit/CachedBuilderTest.php` function `testValueModelResultsCreatesCache` was caching stuff under the specific key that was to be tested as well as additional keys as a side effect. One of those additional keys was then mistakenly used in the cache retrieval. The result was not the expected result. But as the result was a container containing the expected value, the first mistake was compounded by extracting the desired value from the returned container. Thus a successful comparison could be made. Test passed. Test was wrong.
In any case, the error was an error of the specific test, it was not systemic. It just so happened that this error was also present in another test. Both tests have previously been fixed. There is nothing to do here.
