### ISSUE TITLE
think I found a bug with where("something", "somevalue") and where("something", "<>", "somevalue")

### ISSUE THREAD

**Issue by vesper8** [GeneaLabs/laravel-model-caching#62]
One part of my application seems to be broken since I started using this package. I've isolated the problem now

I have a table with 300 records

```
$records = Place::where('place_id', $placeId)->get();
```

$records->count() is = 1 here

then below I run

```
$records = Place::where('place_id', '!=', $placeId)->get();
```

I tried with '<>' but that is the same as '!='

$records->count() should be 299 now, but instead it uses the cache from the above query and returns the same as the above query.. so count is 1.. and instead of getting "Every other record" it is just returning the same record

So it looks like it doesn't differentiate between the two

**Comment by mikebronner** [comment]
Thanks @vesper8 ! I will look into that as soon as possible (I'm currently out of town and will return next week). It looks like I need to differentiate the where clauses better. Thanks so much for reporting this. :)

**Comment by vmosoti** [comment]
seems like a bug when using `where` with other operators including `<,>,<=,>=`

**Comment by mikebronner** [comment]
yea, that's my thinking as well

**Comment by vesper8** [comment]
this is a pretty dangerous bug that's easy to miss and can cause a lot of problems.. hope you can fix it soon :)

**Comment by mikebronner** [comment]
Yea, sorry about the delay ... I have been out of the office most of the last month. Will try to get to it this week. :|

**Comment by mikebronner** [comment]
@vesper8 Thanks for being patient. Can you verify that 0.2.19 fixes this issue? Thanks! :)

**Comment by mikebronner** [comment]
Ah yes, those are on the docket for review. Can you you submit those as a PR, then we can discuss them there? That would be awesome!

**Comment by vesper8** [comment]
@mikebronner I just made a PR for one of the changes

As for the other.. I'm confused.. I tried to "blame" on the CachedKey.php but I can't figure out in which commit you removed the line

```

$value .= "_" . array_get($where, 'value');
```

which is last shown in this commit https://github.com/GeneaLabs/laravel-model-caching/commit/e150f28786fb37322e315c62cf55ea0f8c3c12b2

Since this is the line that I needed to follow up with

```
 if (is_array($value)) {
     $value = implode("_", $value);
 }
```

Which could be more elegantly adapted to

```
$value .= "_" . (
is_array(array_get($where, 'value')) ? implode("_", array_get($where, 'value')) : array_get($where, 'value'))
```

or maybe you can come up with something even nicer

**Comment by mikebronner** [comment]
Hi @vesper8 , that line was removed a few releases ago. The functionality has been moved into the getValues (or similar, I'm not at my computer right now) method further down. I plan on redoing how the keys are built up anyway, so it likely won't matter anymore then.
