### ISSUE TITLE
Identical values on different whereBetween queries

### ISSUE THREAD

**Issue by jetwes** [GeneaLabs/laravel-model-caching#68]
# Issue
* 
`$start_quarter = '2018-01-01'; 
$end_quarter = '2018-03-31';
$start_month = '2018-02-01'; 
$end_month = '2018-02-29';`
Query1   ```
$sales['quarter'] = SaleItem::whereBetween('created_at', [$start_quarter, $end_quarter])
            ->whereIn('shop_id', $shops)
            ->whereIn('sku', $s_products)
            ->count(); 
```
Query2: ```
        $sales['month'] = SaleItem::whereBetween('created_at', [$start_month,$end_month])
            ->whereIn('shop_id', $shops)
            ->whereIn('sku', $s_products)
            ->count();
```
I receive identical values for both queries...
The queries are fired straight after another and the result is the same in both queries...
Can i provide a custom tag or something? If $shops or $s_products changes the result is fine, but if the one of the dates is different the result is the same...
Error: *`

## Environment
Laravel Version: *5.5.34*
Laravel Model Caching Package Version: *0.2.22*
PHP Version: *7.1.14*

**Comment by jetwes** [comment]
when i change the queries to 
` $sales['month'] = SaleItem::where('created_at','>=',$start_month)
            ->where('created_at','<=',$end_month)
            ->whereIn('shop_id', $shops)
            ->whereIn('sku', $s_products)
            ->count();`
the result is correct. Maybe it's related to my previously reported isse #66

**Comment by mikebronner** [comment]
@jetwes You are probably right. I will check the whereBetween code. Thanks for reporting!

**Comment by mikebronner** [comment]
Same problem as with #66. Will be fixed when that fix is released. Will be in next patch in the next day or so.

**Comment by jetwes** [comment]
great - i manually did the fix on my dev enviornment - works as intended. Thank you!

**Comment by mikebronner** [comment]
@jetwes please give version 0.2.23 a try and let me know if that fixes it :)

**Comment by jetwes** [comment]
brilliant, thank you
