### ISSUE TITLE
Doesn't consider Dates or Times in Queries ?

### ISSUE THREAD

**Issue by johnpaulmedina** [GeneaLabs/laravel-model-caching#70]
# Issue
The cache key should consider dates and times passed within a query. For instance I am running a query like so that gets data between certain days and between certain hours of those days. Where $this represents a user model. I noticed that the cache comes back the same number of results for that user no matter the change in the query dates. Is this normal behavior or have I done something wrong on my end?

I am going to look into the laravel-model-caching package now. 

## Environment
Laravel Version: 5.6.3
Laravel Model Caching Package Version: ^0.2.22
PHP Version: 7.1.12
Homestead Version: N/A
Operating System & Version: Mac OS X High Sierra 10.13.3 

## Stack Trace
```
$this->commissioned()
         ->whereDate( 'created_at', '>=', $start_date )
         ->whereDate( 'created_at', '<=', $end_date   )
         ->whereTime( 'created_at', '>=', $start_time )
         ->whereTime( 'created_at', '<=', $end_time   )
         ->paid()
         ->outbound()
         ->get();
```

**Comment by jetwes** [comment]
sounds like the same issue than in #68 and #66

**Comment by mikebronner** [comment]
Thanks for reporting this @johnpaulmedina ! I will make sure this is also looked at and will work on a solution. A fix will be in the next patch!

**Comment by mikebronner** [comment]
@johnpaulmedina please give version 0.2.23 a try and let me know if that fixes it :)

**Comment by johnpaulmedina** [comment]
@mikebronner Thanks! I am pulling the package now. I hadn't had a chance to patch it and send a pr. 

Will let you know how it works for me.
