### ISSUE TITLE
Why php > 7.1 requirement and not > 7.0?

### ISSUE THREAD

**Issue by blomdahldaniel** [GeneaLabs/laravel-model-caching#71]
Dude! This is so great!
I have created something similar myself in two different projects but this solves it in a much cleaner way. Glad to see your solutions! 😃 

I wonder though, why do you force php 7.1? Why not go for the broader audience and allow also php 7.0?

Thanks again for sharing your stuff!

**Comment by mikebronner** [comment]
Hi @blomdahldaniel! It's always tough to decide how to determine dependency restrictions. In this case I always determine required PHP version by the highest PHP version required by compatible Laravel versions or dependencies. In this case it is Laravel 5.6 that requires PHP 7.1.3. :) Also, I try to only support active PHP versions (7.0.x only receives security updates anymore and is on its way out, see here: https://secure.php.net/supported-versions.php).

I'm glad to hear that you like the package though! And thanks for reaching out. :)

**Comment by blomdahldaniel** [comment]
Thanks for a great response and that you clarified this. Thanks again for
sharing your work!


Den ons 14 feb. 2018 00:52Mike Bronner <notifications@github.com> skrev:
