### ISSUE TITLE
The lib is returning null to a attribute of Polygon type

### ISSUE THREAD

**Issue by lucmousinho** [GeneaLabs/laravel-model-caching#73]
# Issue
The lib is returning null to attributes of type Polygon (Mysql). The Polygon type is saved in blob format in mysql database, and the lib is saving the blob as null (or as hex, I'm still analyzing) in redis.

## Environment
Laravel Version: *5.5*
Laravel Model Caching Package Version: *0.2.23*
PHP Version: *7.2*
Operating System & Version: *Ubuntu 16.04*

**Comment by mikebronner** [comment]
@lucmousinho thanks for reporting! Can you provide the full query that you are running? Thanks! (Both in SQL as well as the Eloquent-query-chain)

**Comment by mikebronner** [comment]
Closing this for now, as no response has been provided. Please feel free to re-open if the problem persists. :)
