### ISSUE TITLE
Unit tests are actually Integration tests

### ISSUE THREAD

**Issue by andrewmclagan** [GeneaLabs/laravel-model-caching#77]
# Issue
In the test suite there is one folder containing tests `tests/Unit`.

These are not unit tests as they interact with an external service integration. Thus they are `tests/Integration` tests because they touch either SQLite or MySQL implementation.

## Solution
Rename tests folders to represent the tests they actually perform.

**Comment by mikebronner** [comment]
Will consider this. I completely understand where you are coming from.
