### ISSUE TITLE
Cache key namespacing pattern

### ISSUE THREAD

**Issue by andrewmclagan** [GeneaLabs/laravel-model-caching#78]
# Issue
They cache keys and naming scheme is quite hard for developers to read and does not follow any recognisable pattern e.g. 'genealabslaravelmodelcachingtestsfixturesbook' 

## Solution

It would be more readable and best practice to follow a cache key namespacing architecture as those recommended by Redis.

e.g.

`genealabs:model-caching:test-fixtures:book`

**Comment by mikebronner** [comment]
Actually, the cache keys are hashed versions of the key, but the tags aren't. Ian thinking of changing the way the keys are generated anyway.

**Comment by mikebronner** [comment]
@andrewmclagan This is now implemented in version 0.3.31. Thanks!
