### ISSUE TITLE
disableCache() only works sometimes

### ISSUE THREAD

**Issue by mikassi** [GeneaLabs/laravel-model-caching#83]
# Issue
When calling disableCache() on a query that uses a custom scope (I think this is what's causing it) it only works sometimes.

## Environment
Laravel Version: *5.6.3*
Laravel Model Caching Package Version: *0.2.33*
PHP Version: *7.2.2*
Homestead Version: *N/A*
Operating System & Version: *macOS High Sierra 10.13.3*

## Stack Trace
As you can see the following query works on and off. After it fails it will work and vice-versa.

![disablecache -test0](https://user-images.githubusercontent.com/23439238/36439949-5264324c-1666-11e8-960b-fc23bbd9b6ca.png)

The scope pendingGroupInvites is defined by:
```
public function scopePendingGroupInvites($query, $groupID)
{
    return $query->where([['type', GroupInvite::class], ['data->group->id', $groupID]])->whereNull('data->action');
}
```

The following query always works:

```
Group::find(1)->users()->disableCache()->get();
```

In this case users is a many-to-many relationship.

As a final note, I'm using Redis.

[disableCache()-stacktrace.txt](https://github.com/GeneaLabs/laravel-model-caching/files/1740902/disableCache.-stacktrace.txt)

**Comment by mikassi** [comment]
I updated the initial post with more info.

Also, I think I caught what's causing it. In the following screenshot you can see that sometimes a Builder instance is created but other times a CachedBuilder instance is created:

![disablecache -test1](https://user-images.githubusercontent.com/23439238/36439744-b5493b74-1665-11e8-8ba0-3ffc450a6cbb.png)

Note that the queries are exactly the same and were executed one after another.

**Comment by mikebronner** [comment]
Thanks for the updates. I will look into this later on today. :)

**Comment by mikebronner** [comment]
Hi @mikassi, could you try again using release 0.2.34? I have gone through and done some refactoring and quite a bit of cleanup. Please let me know how that works for you. :)

**Comment by mikassi** [comment]
@mikebronner, It's fixed, thank you very much!

**Comment by mikebronner** [comment]
Great to hear! Thanks for letting me know :)
