### ISSUE TITLE
Cache Doesn't invalidate

### ISSUE THREAD

**Issue by hendra1** [GeneaLabs/laravel-model-caching#87]
# Issue
I've run Product::find(1)
and run Product::find(2)

but the result of the query is collection of product 1
the cache doesn't invalidate automatically

In my Product.php:

`
namespace App\Models;

use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes, Cachable;`

## Environment
Laravel Version: *5.6.3*
Laravel Model Caching Package Version: *0.2.33*
PHP Version: *7.2.0*
Homestead Version: *x.y*
Operating System & Version: *Ubuntu 16.0.4*

**Comment by mikebronner** [comment]
@hendra1 Thank you for submitting this! I will look into this tonight. Thanks for providing exact examples and code. :) That helps!

**Comment by mikebronner** [comment]
I have been able to replicate the problem and am looking into a fix.

**Comment by mikebronner** [comment]
Fix found, will be in next patch.

**Comment by mikebronner** [comment]
Should be fixed in version 0.2.35. Please let me know if it works for you now. Thanks! :)

**Comment by hendra1** [comment]
@mikebronner 
thanks for the patch
now it's work like a charm
