### ISSUE TITLE
Cache doesn't invalidate when using insert method

### ISSUE THREAD

**Issue by hendra1** [GeneaLabs/laravel-model-caching#90]
# Cache  Invalidate Failed

When using insert method for multiple records the cache doesn't invalidate.
The records successfully created, but not the cache.
I'm curious is there a way to clean up the cache from the controller side, not from the command line?
since the cache doesn't invalidate well..

Thanks

## Environment
Laravel Version: *5.6.5*
Laravel Model Caching Package Version: *0.2.35*
PHP Version: *7.2.0-1*
Homestead Version: *x.y*
Operating System & Version: *Ubuntu16.04.1*

## Stack Trace
```
        $input = [
    [
        "product_id" => 2,
    "user_id" => 51,
    "quantity" => 1,
    "information" => [
        "color" => [
        "id" => 1,
        "name" => "White",
      ],
      "size" => [
        "id" => 1,
        "name" => "S (Small)"
      ],
    ],
    "branch" => "jakarta"
  ],
  [
        "product_id" => 4,
    "user_id" => 51,
    "quantity" => 1,
    "information" => [
        "color" => [
        "id" => 2,
        "name" => "Black",
      ],
      "size" => [
        "id" => 1,
        "name" => "S (Small)",
      ]
    ],
    "branch" => "jakarta"
  ]
];
return $this->cart->insert($input);
```

**Comment by mikebronner** [comment]
@hendra1 thanks for reporting this. Could you test again using the latest version of this package: 0.2.40? Thanks!

**Comment by hendra1** [comment]
Yes I did.. and the result is still same.

**Comment by mikebronner** [comment]
Thanks, I will try to replicate it.

**Comment by mikebronner** [comment]
Hi @hendra1,

Regarding your question about having a way to invalidate in the controller: that is not planned. The package should invalidate.

I am unable to recreate the problem with the following test:
```php
    public function testModelCacheDoesInvalidateWhenNoCooldownPeriod()
    {
        $authors = (new Author)
            ->get();

        factory(Author::class, 1)->create();
        $authorsAfterCreate = (new Author)
            ->get();
        $uncachedAuthors = (new UncachedAuthor)
            ->get();

        $this->assertCount(10, $authors);
        $this->assertCount(11, $authorsAfterCreate);
        $this->assertCount(11, $uncachedAuthors);
    }
```

The test passes. Could you provide the queries you are running, specifically the initial query, the insert query, and the third query that is not getting the updated values?

Thanks!

**Comment by mikebronner** [comment]
I found an issue, it has to do with insert. This test exposes it:
```php
    public function testInsertInvalidatesCache()
    {
        $authors = (new Author)
            ->get();

        $newAuthor = (new Author)
            ->insert([
                'name' => 'Test Insert',
                'email' => 'none@noemail.com',
            ]);
        $authorsAfterInsert = (new Author)
            ->get();
        $uncachedAuthors = (new UncachedAuthor)
            ->get();

        $this->assertCount(10, $authors);
        $this->assertCount(11, $authorsAfterInsert);
        $this->assertCount(11, $uncachedAuthors);
    }
```

I will work on fixing this ASAP!

**Comment by mikebronner** [comment]
@hendra1 this should now be fixed in 0.2.41. Thank you so much for reporting this! The insert and update methods hadn't been accounted for yet.

**Comment by hendra1** [comment]
Hi Mike

Thanks for the update.. now it's work  :)

**Comment by mikebronner** [comment]
Awesome! That's great to hear. :) please let me know if you run into any other issues .

**Comment by mrahmadt** [comment]
I'm using 
`
    DB::insert();
`
to insert hundreds of records (this provide faster insert than MODEL::insert, any chance I can invalidate the cache?

**Comment by mikebronner** [comment]
Hi @mrahmadt, could you open a new issue for this? Thanks!
